### PR TITLE
Workaround broken circleci/mongo:3.2-ram image

### PR DESCRIPTION
**Pull request by zachmullen**
See https://github.com/circleci/circleci-images/issues/143

### CODE REVIEW

**Comment by brianhelba** [comment]
You could instead just remove the command entirely for now.

**Comment by zachmullen** [comment]
Tried that first, same error.

**Comment by brianhelba** [comment]
We could just just the non-RAM image for now.

I don't feel strongly right now though.

**Comment by zachmullen** [comment]
I plan to revert whatever we do on this topic as soon as possible, so I think we should just merge this since it fixes the issue.

**Comment by zachmullen** [comment]
@brianhelba did your fix get upstreamed to docker hub yet? If so I will make a revert PR.

**Comment by brianhelba** [comment]
The fix is merged: https://github.com/circleci/circleci-images/pull/144

I'd suggest opening a revert PR, and seeing if it passes, as there's a slim possibility that rebuilds and cache flushing needs more time to occur.

**Pull request merged**
