### PR TITLE
Serve our own license badge

### PR DESCRIPTION
**Pull request by zachmullen**
Two separate services have now failed us for serving up this badge.
It's only 749 bytes and it's ASCII... we'll do it ourselves.

/rant

### CODE REVIEW

**Comment by jbeezley** [comment]
That doesn't appear to be working either: https://github.com/girder/girder/blob/serve-own-license-badge/README.rst

**Comment by zachmullen** [comment]
I think it won't until we merge it, since the rst builder is changing the image path

**Comment by jbeezley** [comment]
Well, it can't be any worse than the current badge.  LGTM.

**Comment by brianhelba** [comment]
LGTM.

**Pull request merged**
