### PR TITLE
Front page refresh

### PR DESCRIPTION
**Pull request by Pierre-Assemat**
This PR start from the brilliant work of @jeffbaumes. The first scope is to change all the style of the front page view.

EDIT: This PR update all the core views of Girder, clean up the css & assure a responsive behavior for each page.

### CODE REVIEW

**Comment by Pierre-Assemat** [comment]
The first step is the `header`. I try to make it the more friendly as possible.

### Full page

screenshot-2017-12-18 girder

---

screenshot-2017-12-18 girder 5
### Medium

screenshot-2017-12-18 girder 1
### Small
screenshot-2017-12-18 girder 2

### Very small
screenshot-2017-12-18 girder 3

### Teeny
screenshot-2017-12-18 girder 4


This work only for non admin.

**Comment by brianhelba** [comment]
@Pierre-Assemat Many of your commits in this branch seem to be made with an invalid email address in the Git metadata. Please address this via rebase, to ensure `git blame` works correctly.

**Comment by Pierre-Assemat** [comment]
Some improvement proposition : 

## Sort collection widget
### Current : 
screenshot-2018-1-16 girder
---
### Proposition :
screenshot-2018-1-16 girder 1

**Comment by Pierre-Assemat** [comment]
The Homepage plugin work well with these changes as you can see : 

screenshot-2018-1-17 the brand name can also be very very long until this break the header layout
---
When the screen is shrunk the Title is hidden : 

screen shot 2018-01-17 at 12 20 11
---
Even in small screen, Girder can be used : 

screen shot 2018-01-17 at 12 23 05

**Comment by jeffbaumes** [comment]
Looks good. Can you also test with the item_tasks plugin enabled, to see if the Tasks navigation menu item is added as expected?

**Comment by Pierre-Assemat** [comment]
Yes I will test that, but I just notice the `html(renderMarkdown...` cause some issue when shrink the screen. I will have to fix it, but I don't know how yet.

screen shot 2018-01-17 at 12 47 25

**Comment by Pierre-Assemat** [comment]
I noticed a breaking change due to the collection description...

I tried to fix it as I can, here how this is handle now: 

screenshot-2018-1-25 girder

screenshot-2018-1-25 girder 1

What do you think ?

**Comment by Pierre-Assemat** [comment]
I think this PR is ready to be reviewed @jeffbaumes!!

**Comment by Pierre-Assemat** [comment]
After many discussion, we decided to develop a completely new UI using new technologies like React or Vue. That's why this branch is no longer useful.

**Pull request closed without merging**
