### PR TITLE
add version number escaping in grunt_tasks/plugin.js

### PR DESCRIPTION
**Pull request by opadron**
Fixes an issue where the version numbers for dependencies listed in a plugin's `plugin.json` file are not properly escaped prior to passing to grunt.

### CODE REVIEW

**Comment by opadron** [comment]
@girder/developers PTAL

**Comment by mgrauer** [comment]
@opadron Is it possible to test this?

Could you add the deleted comment back in and add a comment in the fix about what it is doing and why?

**Comment by zachmullen** [comment]
LGTM

**Comment by mgrauer** [comment]
Nice tests @opadron

**Comment by opadron** [comment]
I wish there was a good spell checker for source code. :(

**Comment by opadron** [comment]
@mgrauer LGTY? :)

**Comment by mgrauer** [comment]
yes indeed

**Pull request merged**
