### PR TITLE
Appends enabled plugins list to plugins variable

### PR DESCRIPTION
**Pull request by kotfic**
Also changes fn_ENABLEDPLIGINS to fn_ENABLEDPLUGINS

### CODE REVIEW

**Comment by zachmullen** [comment]
Nice change, looks like this never would have worked before :)

**Comment by zachmullen** [comment]
LGTM once travis passes

**Comment by kotfic** [comment]
@zachmullen if you can merge this that would be great,  i don't have write access on girder.  Thanks!

**Comment by zachmullen** [comment]
I have invited you to the group that has write access

**Pull request merged**
