### PR TITLE
Add a superclass constructor call to the API's Resource class

### PR DESCRIPTION
**Pull request by brianhelba**
This fixes a warning during Girder startup.

### CODE REVIEW

**Comment by zachmullen** [comment]
LGTMITIH

**Comment by brianhelba** [comment]
>  LGTMITIH

Neither me nor Google know what that means, but it matches ``/^LGTM.*$/`` and the tests pass.

Merging.

**Comment by jeffbaumes** [comment]
Oh, I think I know: "if travis is happy"

**Comment by zachmullen** [comment]
:bell: :bell: :bell: That's a bingo!

**Comment by cpatrick** [comment]
@mgrauer pulled this one out in another PR:

> TIRFMPBIWTTADITPRWI

I'm lost...

**Comment by jbeezley** [comment]
My favorite part of searching google for that acronym is there are two results, each of which are in German text.

**Comment by zachmullen** [comment]
fo**lgt mit Ih**rem

**Comment by jeffbaumes** [comment]
Need to stop now or else I'll try Googlewhacking all afternoon https://en.wikipedia.org/wiki/Googlewhack

**Comment by mgrauer** [comment]
@cpatrick It means `this is ready from my perspective but I want to trigger a discussion in the PR with it`.

It was actually a @jbeezley innovation.  I stood on the shoulders of giants.

**Comment by mgrauer** [comment]
> LGTMITIH

I was going to criticize @zachmullen for being too obvious.

**Comment by jbeezley** [comment]
ISOIA (I speak only in acronyms).

**Pull request merged**
