### PR TITLE
Allow vagrant playbooks to require asset build

### LINKED ISSUE #1796: Girder fails to start in default 'vagrant up' deployment
Girder fails to start in the default 'vagrant up' deployment for development.

To reproduce, follow documentation to set up Girder development environment:
http://girder.readthedocs.io/en/latest/development.html#vagrant

```
$ vagrant up
...
```
Expected result: Browsing to http://localhost:9080/ shows Girder web front-end.
Actual result: Browsing to http://localhost:9080/ shows `500` errors loading Girder resources.

Traceback when running `python -m girder`:
```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 68, in __call__
    raise x
TypeError: 'BaseWebroot' object is not callable
```

### PR DESCRIPTION
**Pull request by danlamanna**
Fixes #1796 

@msmolens PTAL

In a nutshell, these were working correctly for production machines: only ever rebuild if a git clone/pull results in changed files. However with Vagrant, since the repo is mounted and we don't pull (in fear of messing up a devs working tree), there never are any changed files, and the code is never rebuilt.

### CODE REVIEW

**Comment by msmolens** [comment]
`vagrant up` for a development now works as expected for me. Thanks, @danlamanna!

I think we should also consider updating the docs at http://girder.readthedocs.io/en/latest/development.html#vagrant:

> Once this process is complete, you can run vagrant ssh in order to start Girder.

:point_up_2:  Misleading. Girder is already running.

> There is a helper script in the Vagrant home directory that will start Girder in a detached screen session

:point_up_2:  This must be https://github.com/girder/girder/blob/master/devops/ansible/start_girder_in_screen.sh, which seems like a legacy script that should be removed.

.

**Comment by danlamanna** [comment]
Yikes, you're right. I didn't actually know we had a section for Vagrant in the development docs, the ones I wrote exist in the Administrator/Provisioning section: http://girder.readthedocs.io/en/latest/provisioning.html. I'll update them.

**Comment by zachmullen** [comment]
@msmolens I like to view your finger-pointing emoji as a reference to Plato in [The School of Athens](https://upload.wikimedia.org/wikipedia/commons/9/94/Sanzio_01.jpg).

**Comment by danlamanna** [comment]
@msmolens one last look?

**Comment by danlamanna** [comment]
@zachmullen We might also want to look into pruning https://github.com/girder/girder/tree/master/cmake at some point :cry:.

**Comment by zachmullen** [comment]
Indeed, I'll put in a PR.

**Pull request merged**
