### PR TITLE
Make CONTRIBUTING an RST file

### PR DESCRIPTION
**Pull request by brianhelba**
* Make CONTRIBUTING an RST file
* Move the "How to integrate a PR" downwards in CONTRIBUTING
  * Testing comes before merging
* Add CHANGELOG info to CONTRIBUTING
* Convert some Markdown files to reStructuredText

Addresses part of #2344

### CODE REVIEW

**Comment by mgrauer** [comment]
The changelog could go into the how to integrate a PR section, between the two current bullet points, so

 * all tests pass
 * any significant changes are added to the CHANGELOG.rst with human readable and understandable text, i.e. not a commit message, in the "Unreleased" section, and grouped into the appropriate section among 
    * Bug fixes
    * Security fixes
    * Added features
    * Changes
    * Deprecations
    * Removals
 * Consensus is reached. This requires that a reviewer adds an "approved" review via GitHub with no  changes requested, and a reasonable amount of time passed without anyone objecting.

**Comment by danlamanna** [comment]
ref #2344

**Comment by jeffbaumes** [comment]
Can we change "All tests pass" with "Tests and documentation for new or updated code have been added where reasonable, and all tests pass"?

**Comment by mgrauer** [comment]
I went back and reread the third bullet point

>Consensus is reached. This requires that a reviewer adds an "approved" review via GitHub with no changes requested, and a reasonable amount of time passed without anyone objecting.

We don't do the reasonable amount of time part, sometimes PRs are submitted and merged very quickly.  Do we want to add in a "cooling off" period to our PR process, or drop this advice, or is it sufficiently vague and at least enough of a nod in a desirable direction that we should keep it as is?

**Comment by zachmullen** [comment]
"Reasonable amount of time" is left intentionally vague, the intent being to avoid having to dictate hard-and-fast policies that would necessarily slow down development. This methodology puts it in the hands of developers to evaluate risk on an ad hoc basis, in much the same way phrases like these are employed in the legal system. I certainly trust our core dev team's judgment enough to feel comfortable with the status quo.

**Comment by brianhelba** [comment]
@girder/developers @mgrauer PTAL.

**Comment by brianhelba** [comment]
@mgrauer Can you approve again? I pushed one more commit to fix an oversight @zachmullen noticed.

**Comment by mgrauer** [comment]
Good 👁  Mullen.

**Pull request merged**
