### PR TITLE
Fix a bug where private users could not upload to existing items

### LINKED ISSUE #657: Uploading a new file to an existing item as a private user fails
Here's an abbreviated stack trace:
* Upload.finalizeUpload https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/upload.py#L112
* User.load(id=<private_user's_id>, level=AccessType.READ)
* AccessControlledModel.load(id=<private_user's_id>, level=AccessType.READ) https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/model_base.py#L674
* AccessControlledModel.requireAccess(doc=<user_doc>, user=None, level=AccessType.READ) https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/model_base.py#L632
* AccessControlledModel.requireAccess(doc=<user_doc>, user=None, level=AccessType.READ) https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/model_base.py#L606
* returns False at this point, as "user" is None

### PR DESCRIPTION
**Pull request by brianhelba**
Fixes #657. See the bug report for a stack trace of the failure.

### CODE REVIEW

**Comment by brianhelba** [comment]
@manthey 's commit https://github.com/girder/girder/commit/ceff50dbc4fd76dcc9151dea25a9714ae887a530#diff-9da820093628b314ee681cc26cf34f93R111 was the last to touch this code. I'd be happy to get your approvial.

**Comment by cpatrick** [comment]
It would be awesome if there were a failing-passing test for this to prevent regression :smile_cat:

**Comment by brianhelba** [comment]
@cpatrick Agreed, see my comment on the bug https://github.com/girder/girder/issues/657 .

**Comment by zachmullen** [comment]
I'll write the test. I'm also going to clean up this loading logic to be a lot simpler and just force load the item since we've already been through the access control stuff in the REST layer, so I will close this PR and open a new one.

**Comment by brianhelba** [comment]
@zachmullen Fine with me, thanks.

**Pull request closed without merging**
