### PR TITLE
Upgrade Girder package requirements

### PR DESCRIPTION
**Pull request by brianhelba**
CherryPy changes at:
https://github.com/cherrypy/cherrypy/blob/master/CHANGES.txt

psutil changes at:
https://github.com/giampaolo/psutil/blob/master/HISTORY.rst

Snakebite changes at (raw form):
https://github.com/spotify/snakebite/compare/2.5.1...2.7.1

Remove wheel as a transitive package requirement. Running ``pip install -r girder/requirements.txt`` from a fresh virtualenv does not bring in wheel.

Remove obsolete plugin requirements.txt files, as all plugin requirements are now stored in the top-level
requirements.txt and setup.py files.

Upgrade httpretty, and remove a note of a fixed issue. httpretty appears to have been fixed upstream: gabrielfalcao/HTTPretty#109 even though the issue was not closed.

Upgrade Werkzeug, a transitive dependency of Moto.

Boto changes at:
http://docs.pythonboto.org/en/latest/releasenotes/v2.39.0.html

virtualenv changes at:
https://virtualenv.readthedocs.org/en/latest/changes.html

### CODE REVIEW

**Comment by brianhelba** [comment]
With this PR, all of ``requirements.txt`` are up to date.
~~~
$ piprot ./girder/requirements.txt 
bcrypt (2.0.0) is up to date
boto (2.38.0) is up to date
cffi (1.5.0) is up to date
CherryPy (4.0.0) is up to date
Mako (1.0.3) is up to date
pymongo (3.2) is up to date
PyYAML (3.11) is up to date
requests (2.9.1) is up to date
psutil (3.4.1) is up to date
pytz (2015.7) is up to date
six (1.10.0) is up to date
celery (3.1.19) is up to date
geojson (1.3.1) is up to date
snakebite (2.7.2) is up to date
hachoir-core (1.3.3) is up to date
hachoir-metadata (1.3.3) is up to date
hachoir-parser (1.3.4) is up to date
Pillow (3.1.0) is up to date
amqp (1.4.9) is up to date
anyjson (0.3.3) is up to date
billiard (3.3.0.22) is up to date
kombu (3.0.33) is up to date
MarkupSafe (0.23) is up to date
protobuf (2.6.1) is up to date
pycparser (2.14) is up to date
Looks like you've been keeping up to date, time for a delicious beverage!
~~~

**Comment by brianhelba** [comment]
Two more changes:
*  Remove obsolete plugin requirements.txt files, as all plugin requirements are now stored in the top-level
requirements.txt and setup.py files.
*  Upgrade httpretty, and remove a note of a fixed issue. httpretty appears to have been fixed upstream: gabrielfalcao/HTTPretty#109 even though the issue was not closed.

**Comment by brianhelba** [comment]
Ready for review. This covers all dependencies that are unique to Girder (not shared with Romanesco or Minerva).

**Comment by brianhelba** [comment]
I added one more commit to separate the direct development dependencies from the transitive ones. This basically redoes [@jbeezley 's commit](https://github.com/girder/girder/commit/b56481cdec37bbcda58c30f15881482069e2465f) in a more maintainable way.

**Comment by brianhelba** [comment]
@girder/developers Is ``pep8`` a direct development requirement, or just a transitive requirement of ``flake8``? I can't find any direct use of the ``pep8`` tool.

**Comment by jbeezley** [comment]
`pep8` is an [explicit dependency](https://github.com/PyCQA/flake8/blob/master/setup.py#L53) of `flake8`.  I think it would qualify as a transitive requirement.

**Comment by brianhelba** [comment]
@jbeezley I thought so, thanks.

**Comment by brianhelba** [comment]
Rebased on latest master.

**Comment by zachmullen** [comment]
This LGTM but I want to make sure @jbeezley signs off on it.

**Comment by brianhelba** [comment]
Added a few more exclusive-to-Girder packages that very recently released updates.

**Comment by jbeezley** [comment]
I don't think we should get rid of the plugins' requirements files just yet. They aren't just being used for the travis testing environment.  Just looking in this repository we have [several mentions](https://github.com/girder/girder/search?utf8=%E2%9C%93&q=requirements.txt) of files that this removes.  The [`girder-install`](https://github.com/girder/girder/blob/74540e67d933fc7cc1b54b711be8eafb04ea73f7/girder/utility/install.py#L89) relies on these files to install dependencies.  There is also the issue of backward compatibility with downstream plugins that rely on these files.

The changes you made to the top level requirements files are fine though.

**Comment by brianhelba** [comment]
@jbeezley So, we'll have duplicated exact version requirements in both the plugins' requirements.txt, and the top-level requirements.txt, both of which should be manually kept in sync, correct?

Also, we're not currently including the transitive dependencies in the plugins' requirements.txt files. What do you think of this?

**Comment by jbeezley** [comment]
> So, we'll have duplicated exact version requirements in both the plugins' requirements.txt, and the top-level requirements.txt, both of which should be manually kept in sync, correct?

Yes.

> Also, we're not currently including the transitive dependencies in the plugins' requirements.txt files. What do you think of this?

I would keep it this way.  We aren't using the plugins' requirements files for the same purpose as the top level requirements.  The more information we try to pack into these requirements files the more likely it is that we will run into dependency hell.  

Now that I think of it, it is probably best to remove the versions from the plugin's requirement files altogether (except for explicit incompatibilities).  These files are really providing the "abstract dependencies" that would normally be listed in the `setup.py`.

**Comment by zachmullen** [comment]
Is this ready for merge?

**Comment by brianhelba** [comment]
@zachmullen No. To accommodate @jbeezley 's legitimate concerns about the individual plugins' ``requirements.txt`` files, I'm going to simplify this branch to just change all of those individual files to match versions with the updated main ``requirements.txt``.

In another PR, we can address the issue of making those files specify abstract versions, and perhaps clean up some of the duplication in both specification and usage.

**Comment by zachmullen** [comment]
Ok, sounds good. I'll tag this as WIP then.

**Comment by brianhelba** [comment]
PTAL @jbeezley @zachmullen Rebased and simplified this.

**Comment by jbeezley** [comment]
LGTM

**Pull request merged**
