### PR TITLE
Remove deprecated server code

### PR DESCRIPTION
**Pull request by zachmullen**
Note to reviewers: each commit in this topic is an independent change, so it's probably easiest to review them one at a time.

### CODE REVIEW

**Comment by zachmullen** [comment]
@girder/developers this is now ready for review, PTAL.

AFAIK, this is everything for the migration guide. If I've left anything off, please let me know.

**Comment by mgrauer** [comment]
This LGTM.  I'd like to get another set of eyes on 21425d4 before approval, so anyone familiar with Girder's plugin loading and management would be good to look at that.

@zachmullen Did you want to add something in the migration guide related to changes in js test specs, or wait for later PRs?

**Comment by zachmullen** [comment]
I'd like to add a big chunk on web client changes in a subsequent PR, which would include the bit about no longer needing to import your source files manually in test specs.

**Comment by zachmullen** [comment]
@danlamanna would probably be best to look at 21425d4.

**Comment by danlamanna** [comment]
LGTM, sorry for the minor tea party.

**Pull request merged**
