### PR TITLE
Added prerequisites for Arch Linux to the docs

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by zachmullen** [comment]
LGTM, thanks for the update!

**Comment by cpatrick** [comment]
This LGTM. Merging.

**Comment by cpatrick** [comment]
@zachmullen pew pew.

**Comment by cryos** [comment]
Wow that was fast @zachmullen ;-)

**Comment by zachmullen** [comment]
"Move fast and please don't break things."

**Pull request merged**
