### PR TITLE
CentOS support for Girder Ansible role

### PR DESCRIPTION
**Pull request by danlamanna**

### CODE REVIEW

**Comment by kotfic** [comment]
I am seeing strange behavior when trying to run individual tests:

```
$> ctest -VV -R ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_provision
UpdateCTestConfiguration  from :/home/kotfic/kitware/review/girder/ansible-centos-support/_build/DartConfiguration.tcl
Parse Config file:/home/kotfic/kitware/review/girder/ansible-centos-support/_build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/kotfic/kitware/review/girder/ansible-centos-support/_build/DartConfiguration.tcl
Parse Config file:/home/kotfic/kitware/review/girder/ansible-centos-support/_build/DartConfiguration.tcl
Test project /home/kotfic/kitware/review/girder/ansible-centos-support/_build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 194
    Start 194: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_provision

194: Test command: /usr/bin/vagrant "provision"
194: Environment variables: 
194:  GIRDER_EXAMPLE=girder-configure-lib
194:  ANSIBLE_TESTING=1
194:  VAGRANT_BOX=ubuntu/trusty64
194: Test timeout computed to be: 1500
194: ==> default: VM not created. Moving on...
1/1 Test #194: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_provision ...   Passed    1.15 sec

The following tests passed:
	ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_provision
```

Is this expected behavior?

**Comment by danlamanna** [comment]
@kotfic You can't really cherry pick individual tests to run, unfortunately. Not until we use a new enough CMake that we can utilize fixtures. You're trying to run `provision` against a VM that hasn't run `up` yet.

**Comment by danlamanna** [comment]
@kotfic Looking at it now, the provision tests should fail.

I'll alter the `FAIL_REGULAR_EXPRESSION` for provision and destroy tests to fail if `VM not created` is in the output.

**Comment by kotfic** [comment]
I have run the full test suite three times now,  the first run i had two failures:

```
ctest -L girder_ansible
Test project /home/kotfic/kitware/review/girder/ansible-centos-support/_build                              
      Start 193: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_up
 1/18 Test #193: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_up ............   Passed   16.62 sec
      Start 194: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_provision
 2/18 Test #194: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_provision .....***Failed  230.32 sec
      Start 195: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_destroy
 3/18 Test #195: ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_destroy .......   Passed    4.72 sec
      Start 196: ansible_example_centos/7_girder-configure-lib_vagrant_up
 4/18 Test #196: ansible_example_centos/7_girder-configure-lib_vagrant_up ...................   Passed  153.93 sec
      Start 197: ansible_example_centos/7_girder-configure-lib_vagrant_provision
 5/18 Test #197: ansible_example_centos/7_girder-configure-lib_vagrant_provision ............   Passed  333.38 sec
      Start 198: ansible_example_centos/7_girder-configure-lib_vagrant_destroy
 6/18 Test #198: ansible_example_centos/7_girder-configure-lib_vagrant_destroy ..............   Passed    5.29 sec
      Start 199: ansible_example_ubuntu/trusty64_girder-dev-environment_vagrant_up
 7/18 Test #199: ansible_example_ubuntu/trusty64_girder-dev-environment_vagrant_up ..........   Passed  107.06 sec
      Start 200: ansible_example_ubuntu/trusty64_girder-dev-environment_vagrant_provision
 8/18 Test #200: ansible_example_ubuntu/trusty64_girder-dev-environment_vagrant_provision ...   Passed  483.59 sec
      Start 201: ansible_example_ubuntu/trusty64_girder-dev-environment_vagrant_destroy
 9/18 Test #201: ansible_example_ubuntu/trusty64_girder-dev-environment_vagrant_destroy .....   Passed    5.87 sec
      Start 202: ansible_example_centos/7_girder-dev-environment_vagrant_up
10/18 Test #202: ansible_example_centos/7_girder-dev-environment_vagrant_up .................   Passed  152.44 sec
      Start 203: ansible_example_centos/7_girder-dev-environment_vagrant_provision
11/18 Test #203: ansible_example_centos/7_girder-dev-environment_vagrant_provision ..........***Failed  448.19 sec
      Start 204: ansible_example_centos/7_girder-dev-environment_vagrant_destroy
12/18 Test #204: ansible_example_centos/7_girder-dev-environment_vagrant_destroy ............   Passed    4.74 sec
      Start 205: ansible_example_ubuntu/trusty64_girder-nginx_vagrant_up
13/18 Test #205: ansible_example_ubuntu/trusty64_girder-nginx_vagrant_up ....................   Passed   99.30 sec
      Start 206: ansible_example_ubuntu/trusty64_girder-nginx_vagrant_provision
14/18 Test #206: ansible_example_ubuntu/trusty64_girder-nginx_vagrant_provision .............   Passed  326.52 sec
      Start 207: ansible_example_ubuntu/trusty64_girder-nginx_vagrant_destroy
15/18 Test #207: ansible_example_ubuntu/trusty64_girder-nginx_vagrant_destroy ...............   Passed    4.75 sec
      Start 208: ansible_example_centos/7_girder-nginx_vagrant_up
16/18 Test #208: ansible_example_centos/7_girder-nginx_vagrant_up ...........................   Passed  149.28 sec
      Start 209: ansible_example_centos/7_girder-nginx_vagrant_provision
17/18 Test #209: ansible_example_centos/7_girder-nginx_vagrant_provision ....................   Passed  347.56 sec
      Start 210: ansible_example_centos/7_girder-nginx_vagrant_destroy
18/18 Test #210: ansible_example_centos/7_girder-nginx_vagrant_destroy ......................   Passed    4.64 sec

89% tests passed, 2 tests failed out of 18

Label Time Summary:
girder_ansible    = 2878.20 sec (18 tests)

Total Test time (real) = 2878.23 sec

The following tests FAILED:
	194 - ansible_example_ubuntu/trusty64_girder-configure-lib_vagrant_provision (Failed)
	203 - ansible_example_centos/7_girder-dev-environment_vagrant_provision (Failed)
```

The other two times I have had no failures.  Not sure what to make of that.

**Pull request merged**
