### PR TITLE
Prefer downloading external test data from data.kitware.com

### PR DESCRIPTION
**Pull request by brianhelba**
* Prefer downloading external test data from data.kitware.com
* Use SHA512 external data keyfiles, to ensure downloading from data.kitware
* Include a trailing newline in hashsum download keyfiles
* Update the external data docs to reference data.kitware.com workflow
* Consistently refer to "external data artifacts" in documentation
* Stop referring to all tests as "unit tests" in docs

### CODE REVIEW

**Comment by brianhelba** [comment]
Pushed 3 more commits to update docs.

**Comment by brianhelba** [comment]
GitHub is being slow to update for me right now, but there should be a total of 6 commits now in this branch. PTAL.

**Comment by jbeezley** [comment]
I think you need to update this line as well: https://github.com/girder/girder/blob/master/tests/CMakeLists.txt#L111

**Comment by brianhelba** [comment]
@jbeezley Fixed.

**Pull request merged**
