### PR TITLE
Add button to UI for inline file viewing

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
ping @ronichoudhury

**Comment by fogleman** [comment]
Would `icon-eye` be better?

**Comment by zachmullen** [comment]
screen shot 2016-06-21 at 2 15 23 pm

**Comment by fogleman** [comment]
It'd be nice if this icon was on the left near the filename (which is the download link) since downloading & viewing are similar actions.

**Comment by fogleman** [comment]
Maybe even with text, like `[Download File | View in Browser]`

**Comment by zachmullen** [comment]
fixes #309

**Comment by fogleman** [comment]
LGTM

**Comment by zachmullen** [comment]
After most recent changes:

screen shot 2016-06-21 at 2 44 10 pm

**Comment by ronichoudhury** [comment]
This looks awesome! Though, I did prefer the "link out" icon (don't know its fontello name) to the eye-of-sauron (which I've always found somewhat creepy).

**Comment by zachmullen** [comment]
I'm going to make two comments, please put a thumbs up on the icon you prefer for inline viewing. Calling all @girder/developers

**Comment by zachmullen** [comment]
screen shot 2016-06-21 at 2 55 35 pm

**Comment by zachmullen** [comment]
screen shot 2016-06-21 at 2 55 45 pm

**Comment by ronichoudhury** [comment]
Good lord :smirk_cat:

**Pull request merged**
