### PR TITLE
Fixes #989. Disable cherrypy autoreload unless in dev mode

### LINKED ISSUE #989: Disable cherrypy auto-reload behavior unless we are in "dev" environment
Test and prod modes should not have this behavior.

### PR DESCRIPTION
**Pull request by zachmullen**
@girder/developers PTAL, this is a small change but just want to make sure everyone is OK with it.

### CODE REVIEW

**Comment by jbeezley** [comment]
Seems okay to me.  Does testing use a mode other than `development`?

**Comment by zachmullen** [comment]
@jbeezley It uses a mode called ["testing"](https://github.com/girder/girder/blob/disable-autoreload/girder/utility/server.py#L80-L87).

**Comment by zachmullen** [comment]
Any concerns about this, or should I merge?

**Comment by jbeezley** [comment]
I'll give a LGTM.

**Comment by jcfr** [comment]
Sorry for the last miniute comment. But does this mean that the server will  not restart automatically if a plugin is enabled from the admin console ?

**Comment by zachmullen** [comment]
@jcfr that functionality still works, this only disables the file watcher.

**Comment by jcfr** [comment]
@zachmullen  Makes sense. Thanks for clarifying.

**Pull request merged**
