### PR TITLE
Separate DICOM search by key and value with equal sign

### PR DESCRIPTION
**Pull request by finetjul**
xxx will search xxx in key or value
xxx=yyy will search xxx in key and yyy in key value
xxx\=yyy will search xxx=yyy in key or value

### CODE REVIEW

**Comment by finetjul** [comment]
@jbeezley @zachmullen can you please review ?

**Comment by mgrauer** [comment]
Also @brianhelba as we have a customer relying on DICOM search.

**Comment by zachmullen** [comment]
+1 to have @brianhelba review this since he is the original designer of the DICOM search features.

**Comment by brianhelba** [comment]
Will do.

**Comment by finetjul** [comment]
@brianhelba I don't think my PR is making the tests fails. Feel free to have a look. Thanks.

**Pull request closed without merging**
