### PR TITLE
Add a new CMake macro to define standard plugin tests

### PR DESCRIPTION
**Pull request by brianhelba**
* Add a new macro to define standard plugin tests
* Define most plugin tests with add_standard_plugin_tests
* Add tests for the vega plugin
* Add tests for the jquery_widgets plugin
  * Also, move the server component of the plugin into its own directory, as the documentation specifies.
* Define hdfs_assetstore plugin tests with add_standard_plugin_tests
  * Also, rename hdfs_assetstore server plugin test files to match the convention used by all other plugins.
* Define metadata_extractor plugin tests with add_standard_plugin_tests
* Define thumbnails plugin tests with add_standard_plugin_tests
  * Also, remove special eslint exceptions for the thumbnails plugin, as they are no longer required.
* Define item_tasks plugin tests with add_standard_plugin_tests
  * Also, rename item_tasks client plugin spec files to match the convention used by all other plugins.
* Add a static analysis test for the dicom_viewer plugin's Webpack helper
* Fix style errors found by new plugin static analysis tests

### CODE REVIEW

**Comment by brianhelba** [comment]
This adds 15 new tests for plugins.

**Comment by brianhelba** [comment]
@girder/developers PTAL. This adds additional testing to several plugins while removing boilerplate code.

**Comment by jbeezley** [comment]
It looks like a nice improvement.  Could you add it to the plugin development documentation?

**Comment by brianhelba** [comment]
@jbeezley Sure, I'll update the docs too.

**Comment by brianhelba** [comment]
@jbeezley I've added a final commit to update the documentation. PTAL.

**Comment by brianhelba** [comment]
@jbeezley Since you've reviewed this too, I'll wait for your explicit approval to merge.

**Pull request merged**
