### PR TITLE
Conspicuous public status

### PR DESCRIPTION
**Pull request by zachmullen**
ping @fogleman this supersedes PR #1371

### CODE REVIEW

**Comment by fogleman** [comment]
Very nice, I'll close my PR.

**Comment by brianhelba** [comment]
@zachmullen Got any screenshots?

**Comment by zachmullen** [comment]
screen shot 2016-06-09 at 4 16 55 pm

**Comment by brianhelba** [comment]
Are you going to change the folder listing too, to be consistent? Users seem regularly confused at the distinction between the collection list and a folder list.

**Comment by zachmullen** [comment]
I hadn't planned on it, that's part of the HierarchyWidget which has a different layout altogether.

**Comment by fogleman** [comment]
I agree with @brianhelba. But for the HierarchyWidget I think a yellow background on Private folders would be sufficient. (No need to move the icon.)

**Comment by zachmullen** [comment]
Oh, you just mean the color? I can add that to the HierarchyWidget.

**Comment by zachmullen** [comment]
Done

**Comment by fogleman** [comment]
LGTM

**Pull request merged**
