### PR TITLE
Remove plugin load exception handling and rework plugin tests

### LINKED ISSUE #2316: Guard against plugin webpack errors
If a plugin's `webpack.helper.js` script throws an error, none of the plugins will build.  At the very least, there should be a guard around where `webpackHelper` function is executed.  The offending plugin should probably be marked failing in some manner so that it can't be enabled.

The guard is straightforward:
```
try {
    var newConfig = webpackHelper(baseConfig, helperConfig);
} catch (err) {
    grunt.log.error(`Failed to run webpack helper for ${plugin}: ${err.message}`);
    return;
}
```

I'm not sure how to disable the plugin in this case.

### PR DESCRIPTION
**Pull request by brianhelba**
Closes #2316

### CODE REVIEW

**Comment by manthey** [comment]
This will probably affect development more than anything else.  When we are writing a plugin and have the server in development mode so it restarts when the python files change, if you break the plugin, the girder server currently restarts without the plugin enabled.  Fixing your code then requires restarting the server either via the endpoint or by touching another non-plugin file (or stopping it and starting it again as done originally).

With this change, the server will stop and have to be restarted via the appropriate command.

I don't object to this, but it could change how we work on plugins.

**Comment by danlamanna** [comment]
> When we are writing a plugin and have the server in development mode so it restarts when the python files change, if you break the plugin, the girder server currently restarts without the plugin enabled.

This is a good point. Does it make sense to have custom logic for development mode here? In production I can see not wanting Girder to start if a plugin fails to load as that presents a fatal error in the deployment scenario. In development however, syntax errors are commonplace and shouldn't involve more intervention than fixing the syntax, if possible.

I don't want Girder to be littered with `if mode == development` logic, but it sounds like the extremely common cycle of write some code, test, repeat could be impacted a bit.

**Comment by zachmullen** [comment]
Syntax errors in a plugin are already fatal to Girder startup, because we only catch exceptions that happen during plugin load, not during `entrypoint.load` of the plugin. We should do all-or-nothing behavior there.

**Comment by brianhelba** [comment]
@girder/developers PTAL. This now removes exception handling from both `_loadPlugins` and `_wrapPluginLoad`. This also significantly rewrites the plugin tests to (hopefully) cover more of the cases that the current plugin system actually supports.

**Pull request merged**
