### PR TITLE
[WIP] Add a setting in the web client to allow CORS via restRequest

### PR DESCRIPTION
**Pull request by zachmullen**
@jbeezley Can you let me know whether this fixes your CORS issue? Somewhere in your code before you start the girder app, just add the following line:

`girder.allowCors = true;`

### CODE REVIEW

**Comment by zachmullen** [comment]
Also it occurs to me we may want to change this setting name to `allowCorsAuth`, and also I'd be fine with having it default to `true`.

**Comment by cpatrick** [comment]
This is going to require some documentation :smile_cat:

**Comment by jbeezley** [comment]
I pushed this branch and added `<script>girder.allowCors=true;</script>` after `<script src="./static/built/app.min.js"></script>`, but that didn't solve the problem.

**Comment by jbeezley** [comment]
This is another issue to be aware of when using this: 
```
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://apps.bsvecosystem.net' is therefore not allowed access.
```

**Comment by zachmullen** [comment]
I'm going to close this; the actual solution will not require this flag anyway.

**Pull request closed without merging**
