### PR TITLE
Make some model methods into generators, instead of returning lists

### PR DESCRIPTION
**Pull request by brianhelba**
Also ensure that API endpoints do return lists, instead of generators, and do so using the simpler list constructor syntax when possible.

### CODE REVIEW

**Comment by brianhelba** [comment]
Marking this as WIP for now. Some of the test code needs to be updated to not call len() on generators.

**Comment by brianhelba** [comment]
PR is ready for review.

**Comment by brianhelba** [comment]
@zachmullen @manthey No pressure, but this is ready for review.

**Comment by zachmullen** [comment]
LGTM!

**Pull request merged**
