### PR TITLE
Fix multipart uploads for s3

### PR DESCRIPTION
**Pull request by fogleman**
@zachmullen 

I added the `response_headers` clause when I noticed it differed from the boto source: https://github.com/boto/boto/blob/dd5f87c7d5c55b69aa23bb4c21010897eb0deb42/boto/s3/connection.py#L354-L378

But it's possible you removed it intentionally? I didn't check the history. It probably has nothing to do with the error I was getting.

### CODE REVIEW

**Comment by fogleman** [comment]
I was able to reproduced the failure when including all headers, and it works with only content-type header.

**Comment by zachmullen** [comment]
Excellent. It would be nice to figure out exactly which header was causing the problem, but I think it might be better to just plan to migrate to boto3 in the not-too-distant future.

LGTM

**Comment by zachmullen** [comment]
For posterity, this was the issue @jcfr ran into almost a year ago when uploading via the client to an S3 assetstore.

**Comment by jcfr** [comment]
xref #912

Nice. Good to see this being fixed :tada:

**Pull request merged**
