### PR TITLE
Ansible client settings module

### PR DESCRIPTION
**Pull request by danlamanna**
@kotfic Mind taking a look?

### CODE REVIEW

**Comment by kotfic** [comment]
@danlamanna 

I am seeing the following test fail:

```
10: Test command: /home/kotfic/.venvs/girder/bin/ansible-playbook "-i" "/home/kotfic/tmp/girder/clients/ansible/test/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory" "--private-key=/home/kotfic/tmp/girder/clients/ansible/test/.vagrant/machines/girder/virtualbox/private_key" "-u" "vagrant" "test_setting.yml" "-v"
10: Test timeout computed to be: 1500
10: Using /etc/ansible/ansible.cfg as config file
10: 
10: PLAY [girder] ******************************************************************
10: 
10: TASK [setup] *******************************************************************
10: ok: [girder]
10: 
10: TASK [Create 'admin' User] *****************************************************
10: ok: [girder] => {"changed": false, "debug": {"args": ["admin", "letmein"], "kwargs": {"admin": true, "email": "chris.kotfila@kitware.com", "firstName": "Chris", "lastName": "Kotfila"}, "method": "user", "params": {"admin": true, "email": "chris.kotfila@kitware.com", "firstName": "Chris", "lastName": "Kotfila", "login": "admin", "password": "letmein"}}, "gc_return": {"_accessLevel": 2, "_id": "57c096740640fd23b9d3e4b1", "_modelType": "user", "admin": true, "created": "2016-08-26T19:20:20.262000+00:00", "email": "chris.kotfila@kitware.com", "emailVerified": false, "firstName": "Chris", "gravatar_baseUrl": "https://www.gravatar.com/avatar/80b5ccf8ffa30c549ae85da867bcf8be?d=identicon", "groupInvites": [], "groups": [], "lastName": "Kotfila", "login": "admin", "public": true, "size": 0, "status": "enabled"}, "msg": "Success!", "token": ""}
10: 
10: TASK [Disable user default folders] ********************************************
10: changed: [girder] => {"changed": true, "debug": {"args": ["core.user_default_folders"], "kwargs": {"value": "none"}, "method": "setting", "params": {"key": "core.user_default_folders", "value": "none"}}, "gc_return": {"current_value": "none", "previous_value": "public_private"}, "msg": "Success!", "token": "uuB2DvOQy95pF79h1hKuXhqUW7ZOV59XZu9UncX3zUIAX78EFnwc7DexEk8oSw52"}
10: 
10: TASK [Check that user default folders are set to none] *************************
10: ok: [girder] => {"changed": false, "msg": "all assertions passed"}
10: 
10: TASK [Alter the plugin setting] ************************************************
10: changed: [girder] => {"changed": true, "debug": {"args": ["core.plugins_enabled"], "kwargs": {"value": ["jobs", "gravatar"]}, "method": "setting", "params": {"key": "core.plugins_enabled", "value": ["jobs", "gravatar"]}}, "gc_return": {"current_value": ["jobs", "gravatar"], "previous_value": ["gravatar"]}, "msg": "Success!", "token": "6NdclfYXJA1DKbMk41JYbaYqqWnkzSsI7l5WwRP8X2FBjuOkRy75dpiTOMBcfn0H"}
10: 
10: TASK [Check that proper plugins are enabled] ***********************************
10: fatal: [girder]: FAILED! => {"assertion": "ret[\"gc_return\"][\"previous_value\"] == []", "changed": false, "evaluated_to": false, "failed": true}
10: 
10: NO MORE HOSTS LEFT *************************************************************
10: 	to retry, use: --limit @test_setting.retry
10: 
10: PLAY RECAP *********************************************************************
10: girder                     : ok=5    changed=2    unreachable=0    failed=1   
10: 
10/11 Test #10: test_setting .....................***Failed    5.39 sec
```

Let me know what other info you need.

**Comment by kotfic** [comment]
Also please bump the [minor version](https://github.com/girder/girder/blob/b0889a14adbbd2a1393be30dd10d29c42aefa441/clients/ansible/girder.py#L37)

**Comment by kotfic** [comment]
Now i'm seeing:

```
test 10
      Start 10: test_setting

10: Test command: /home/kotfic/.venvs/girder/bin/ansible-playbook "-i" "/home/kotfic/tmp/girder/clients/ansible/test/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory" "--private-key=/home/kotfic/tmp/girder/clients/ansible/test/.vagrant/machines/girder/virtualbox/private_key" "-u" "vagrant" "test_setting.yml" "-v"
10: Test timeout computed to be: 1500
10: Using /etc/ansible/ansible.cfg as config file
10: 
10: PLAY [girder] ******************************************************************
10: 
10: TASK [setup] *******************************************************************
10: ok: [girder]
10: 
10: TASK [Create 'admin' User] *****************************************************
10: ok: [girder] => {"changed": false, "debug": {"args": ["admin", "letmein"], "kwargs": {"admin": true, "email": "chris.kotfila@kitware.com", "firstName": "Chris", "lastName": "Kotfila"}, "method": "user", "params": {"admin": true, "email": "chris.kotfila@kitware.com", "firstName": "Chris", "lastName": "Kotfila", "login": "admin", "password": "letmein"}}, "gc_return": {"_accessLevel": 2, "_id": "57c431970640fd23b49f9284", "_modelType": "user", "admin": true, "created": "2016-08-29T12:59:03.555000+00:00", "email": "chris.kotfila@kitware.com", "emailVerified": false, "firstName": "Chris", "gravatar_baseUrl": "https://www.gravatar.com/avatar/80b5ccf8ffa30c549ae85da867bcf8be?d=identicon", "groupInvites": [], "groups": [], "lastName": "Kotfila", "login": "admin", "public": true, "size": 0, "status": "enabled"}, "msg": "Success!", "token": ""}
10: 
10: TASK [Disable user default folders] ********************************************
10: changed: [girder] => {"changed": true, "debug": {"args": ["core.user_default_folders"], "kwargs": {"value": "none"}, "method": "setting", "params": {"key": "core.user_default_folders", "value": "none"}}, "gc_return": {"current_value": "none", "previous_value": "public_private"}, "msg": "Success!", "token": "4d2JbrIDtf2CAUUeEji5GAUuXVX5kcIKnZ60j4UCknkN148iJxJb2yEO7elPVw83"}
10: 
10: TASK [Check that user default folders are set to none] *************************
10: ok: [girder] => {"changed": false, "msg": "all assertions passed"}
10: 
10: TASK [Alter the plugin setting] ************************************************
10: changed: [girder] => {"changed": true, "debug": {"args": ["core.plugins_enabled"], "kwargs": {"value": ["jobs", "gravatar"]}, "method": "setting", "params": {"key": "core.plugins_enabled", "value": ["jobs", "gravatar"]}}, "gc_return": {"current_value": ["jobs", "gravatar"], "previous_value": []}, "msg": "Success!", "token": "8K1OkFrmvoSmgoWwUjqII39sLnZ5zhQ0zIR3px8OWds8b80DGMSAHX2m85GcOPfy"}
10: 
10: TASK [Check that proper plugins are enabled] ***********************************
10: ok: [girder] => {"changed": false, "msg": "all assertions passed"}
10: 
10: TASK [Set multiple settings for email] *****************************************
10: changed: [girder] => (item={u'key': u'core.email_from_address', u'value': u'girder@girder.girder'}) => {"changed": true, "debug": {"args": ["core.email_from_address"], "kwargs": {"value": "girder@girder.girder"}, "method": "setting", "params": {"key": "core.email_from_address", "value": "girder@girder.girder"}}, "gc_return": {"current_value": "girder@girder.girder", "previous_value": "Girder <no-reply@girder.org>"}, "item": {"key": "core.email_from_address", "value": "girder@girder.girder"}, "msg": "Success!", "token": "7Ib4dyFkxVJMG2ohhxvZeNMPNb0Wh8F6ddeqJm9Qk3ClaA0ud8hS77QdBPJtK7oK"}
10: changed: [girder] => (item={u'key': u'core.email_host', u'value': u'myemailhost'}) => {"changed": true, "debug": {"args": ["core.email_host"], "kwargs": {"value": "myemailhost"}, "method": "setting", "params": {"key": "core.email_host", "value": "myemailhost"}}, "gc_return": {"current_value": "myemailhost", "previous_value": "http://0.0.0.0:8080"}, "item": {"key": "core.email_host", "value": "myemailhost"}, "msg": "Success!", "token": "qtndlqS5KIoUzEUoZAMoKehBmhCOXkGhRU1o8aK7EcxDIhjjS07qf8SWCdJXvPrl"}
10: 
10: TASK [Get email settings] ******************************************************
10: fatal: [girder]: FAILED! => {"changed": false, "failed": true, "msg": "<class 'girder_client.HttpError'>:HTTP error 500: GET http://localhost:8080/api/v1/system/setting?list=core.email_from_address&list=core.email_host\n{\"message\": \"TypeError: TypeError('expected string or buffer',)\", \"trace\": [[\"/opt/girder/master/girder/api/rest.py\", 505, \"endpointDecorator\", \"val = fun(self, args, kwargs)\"], [\"/opt/girder/master/girder/api/rest.py\", 1040, \"GET\", \"return self.handleRoute('GET', path, params)\"], [\"/opt/girder/master/girder/api/rest.py\", 828, \"handleRoute\", \"val = handler(**kwargs)\"], [\"/opt/girder/master/girder/api/access.py\", 47, \"wrapped\", \"return fun(*iargs, **ikwargs)\"], [\"/opt/girder/master/girder/api/v1/system.py\", 138, \"getSetting\", \"keys = json.loads(params['list'])\"], [\"/usr/lib/python2.7/json/__init__.py\", 338, \"loads\", \"return _default_decoder.decode(s)\"], [\"/usr/lib/python2.7/json/decoder.py\", 366, \"decode\", \"obj, end = self.raw_decode(s, idx=_w(s, 0).end())\"]], \"type\": \"internal\"}\nTraceback (most recent call last):\n  File \"/tmp/ansible_MBIIJF/ansible_module_girder.py\", line 1860, in main\n    gcm(module)\n  File \"/tmp/ansible_MBIIJF/ansible_module_girder.py\", line 1108, in __call__\n    self.__process(method)\n  File \"/tmp/ansible_MBIIJF/ansible_module_girder.py\", line 1136, in __process\n    ret = getattr(self, method)(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py\", line 295, in get\n    return self.sendRestRequest('GET', path, parameters)\n  File \"/usr/local/lib/python2.7/dist-packages/girder_client/__init__.py\", line 288, in sendRestRequest\n    text=result.text)\nHttpError: HTTP error 500: GET http://localhost:8080/api/v1/system/setting?list=core.email_from_address&list=core.email_host\n"}
10: 
10: NO MORE HOSTS LEFT *************************************************************
10: 	to retry, use: --limit @test_setting.retry
10: 
10: PLAY RECAP *********************************************************************
10: girder                     : ok=7    changed=3    unreachable=0    failed=1   
10: 
10/11 Test #10: test_setting .....................***Failed    7.74 sec
```

**Comment by danlamanna** [comment]
There were some minor issues with sharing state between playbooks that I cleaned up.

I've run the tests with `--schedule-random` (a lot) and haven't seen any more issues crop up. Making @jbeezley run the tests as well to see if he can reproduce your error (since I can't).

**Comment by jbeezley** [comment]
They all passed for me on ansible 2.1.1.

**Comment by kotfic** [comment]
@danlamanna Upgrading from ansible 2.1.0 to 2.1.1 resolved the issue for me.  That is somewhat disappointing (looking at you ansible) -- regardless LGTM.

**Pull request merged**
