### PR TITLE
Use the STATIC_ROOT_DIR for plugin files, not ROOT_DIR.

### PR DESCRIPTION
**Pull request by manthey**
Also, ignore _testDownload.

### CODE REVIEW

**Comment by zachmullen** [comment]
LGTM

**Comment by zachmullen** [comment]
@manthey would you like to cut a point release? :question:

**Comment by manthey** [comment]
I can.  Should we wait for anything else?

On Thu, May 14, 2015 at 1:49 PM, Zach Mullen <notifications@github.com>
wrote:

> @manthey <https://github.com/manthey> would you like to cut a point
> release? [image: :question:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/pull/846#issuecomment-102115979>.
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by zachmullen** [comment]
I think we are good to go

**Pull request merged**
