### PR TITLE
WIP: Add a script to get Girder public Python symbols

### PR DESCRIPTION
**Pull request by brianhelba**
Based on work by @danlamanna in https://github.com/girder/girder/commit/da3bb202ec5c9093400818be3dc342125504ac7b

### CODE REVIEW

**Comment by brianhelba** [comment]
Output is also dumped here: https://gist.github.com/brianhelba/4c5a43951fc0d853cf54328ac007badc

**Comment by danlamanna** [comment]
ref #2387

**Comment by kotfic** [comment]
Seems like the consensus is this is blocking on incorporation into CI

**Comment by mgrauer** [comment]
@brianhelba is this PR still alive?

**Pull request closed without merging**
