### PR TITLE
Alter plugins page to show unmet dependencies

### LINKED ISSUE #645: Better error message if dependent plugin is missing

### PR DESCRIPTION
**Pull request by danlamanna**
Instead of determining a true/false of whether or not a plugin has its dependencies, gather which of its dependencies were unmet and display them for the user to identify what they're missing.

Related: Kitware/minerva#249 

Fixes #645.

### CODE REVIEW

**Comment by brianhelba** [comment]
I think this will fix https://github.com/girder/girder/issues/645 . Please close that when this is merged.

**Comment by jbeezley** [comment]
For those that are unaware, you can put a comment like "Fixes #xxx" in your PR or on a commit and github will automatically close the linked issue when it is merged.

**Comment by aashish24** [comment]
Thanks @danlamanna !!

**Comment by brianhelba** [comment]
@jbeezley Indeed, https://github.com/blog/1506-closing-issues-via-pull-requests , but just to be precise, the original PR comment needs to have this. I don't believe follow-up comments will trigger it.

**Comment by jbeezley** [comment]
No, follow up comments don't trigger the behavior.  I was just disseminating knowledge for anyone that happened to be listening.

**Comment by danlamanna** [comment]
@aashish24 Mind reviewing this?

**Comment by zachmullen** [comment]
LGTM

**Comment by aashish24** [comment]
> @aashish24 Mind reviewing this?

@danlamanna I couldn't get to it earlier but will report back once we update girder ref in Minerva.

**Pull request merged**
