### PR TITLE
Add script for unzipping zipped items in girder

### PR DESCRIPTION
**Pull request by fogleman**
This is intended to be run after migrating from Midas to Girder.

During migration, Midas items that had multiple "bitstreams" are downloaded as a zip file and stored in Girder as such. This script looks for zip files that are flat (have no folders) and have multiple file entries and unzips them into the same item, removes the zip file, and removes the .zip extension from the item.

I've run the script on QIDW. (Still running actually.)

### CODE REVIEW

**Comment by cpatrick** [comment]
I really like your description here, could you add it as a block comment at the top of the script?

A few other notes:
* Could we add style tests to this scripts directory?
* Could you add a small argparse interface to this?

After that, LGTMWTIH.

**Comment by zachmullen** [comment]
Is there not a way to download the bitstreams from Midas separately?

**Comment by fogleman** [comment]
@zachmullen Not in pydas. Not sure about otherwise.

**Comment by zachmullen** [comment]
That's something we should add to pydas. It would be possible by calling the lower-level `request` method of the driver.

**Comment by fogleman** [comment]
@zachmullen Agreed. I can take a look at some point in the future. For now, this script has done everything I needed.

**Comment by zachmullen** [comment]
I'm going to close this for now since I don't think we'd run it against most girder instances since it acts globally on all .zip files. I've recorded the underlying bug in pydas here: https://github.com/midasplatform/pydas/issues/36

**Pull request closed without merging**
