### PR TITLE
Batch install python deps to detect version collisions

### PR DESCRIPTION
**Pull request by jbeezley**
The `InstallPythonRequirements.py` script originally installed each requirement file one by one.  When two plugins share dependencies or conflict with girder's core dependencies, pip would overwrite the installation each time with the last requirements file processed.  This became apparent in other projects because [romanesco](https://github.com/Kitware/romanesco/blob/master/requirements.txt#L7) currently depends on `pymongo==2.7` which overwrites girder's `3.0` installation.

This PR saves up all requirements files and installs them all at once.  This has the advantage of throwing an error when there is a conflict like this.  Unfortunately, it will also throw an error if two requirements files have the same version of the same package as well.  My opinion is that it is better to raise the error here than try and figure out what went wrong later even if the checks are too strict.

We could parse the requirements files with the less than stable pip python API (`pip.req.parse_requirements`, ...) and resolve conflicts manually, but that seems like more effort than it is worth.

### CODE REVIEW

**Comment by zachmullen** [comment]
LGTM

**Comment by jbeezley** [comment]
Before this goes in, we should plan how to fix minerva + any other projects using the script.  I'm not yet convinced this change is worth the trouble it will cause.

**Comment by zachmullen** [comment]
Hm, that is problematic that you can't even have the exact same version dependency in two different files. Maybe we should close this...?

**Comment by jbeezley** [comment]
I may have an alternate solution depending on how motivated I get during my next flight.

**Pull request closed without merging**
