### PR TITLE
Install travis npm globally not on next branch

### PR DESCRIPTION
**Pull request by mgrauer**
Travis was breaking.

### CODE REVIEW

**Comment by zachmullen** [comment]
Suddenly flake8 stuff is also failing, looks like it's not taking our configuration parameters into account... @girder/developers anyone have ideas why that might be happening?

**Comment by zachmullen** [comment]
@mgrauer I think I found a fix, is it OK to commit it onto this branch?

**Comment by mgrauer** [comment]
:goberserk:

**Comment by zachmullen** [comment]
I'm guessing, with absolutely no effort towards actually figuring out if it's true, that new style edicts were just backported to older versions of pep8.

**Comment by zachmullen** [comment]
@mgrauer this LGTM, merge away if you are OK with my changes

**Comment by mgrauer** [comment]
:maple_leaf:

**Pull request merged**
