### PR TITLE
Don't show exact byte count twice

### LINKED ISSUE #1401: Don't show exact byte count twice
I.e., this case:

screen shot 2016-06-22 at 9 40 04 am

### PR DESCRIPTION
**Pull request by fogleman**
Fixes #1401 @zachmullen

### CODE REVIEW

**Comment by zachmullen** [comment]
I've never been too fond of our convention of using 20000 as the threshold... Is this a common thing? ping @manthey

**Comment by fogleman** [comment]
I just used what was already in place. :shrug: Seems like anything over 1kB could be formatted.

**Comment by zachmullen** [comment]
I would prefer just using 1024 as the max number of bytes before we reformat, just wanted to see if there is some logic behind the choice of 20000.

**Comment by fogleman** [comment]
I doubt there's a specific reason, so I went ahead and made the change.

**Comment by zachmullen** [comment]
LGTM

**Pull request merged**
