### PR TITLE
Clean up the docs on deployment alternatives

### PR DESCRIPTION
**Pull request by brianhelba**
* Drop support for running on Elastic Beanstalk
* Drop support for running on Google Container Engine
* Drop support for running behind Apache
* Rename the Deployment and Deployment Alternatives doc pages
* Rename the deployment-template directory

### CODE REVIEW

**Comment by mgrauer** [comment]
@jamiesnape you are the only one to my knowledge that was running girder in beanstalk. just wanted to give you the heads up that we are trimming out beanstalk docs from the general docs, so you can at least know and also capture those docs if you need to (though they will be in the git history).

**Comment by jcfr** [comment]
Two suggestions:
* document these historical  information on the Girder wiki provided by GitHub (example of text provided below)
* and/or add entries in the [CHANGELOG](https://github.com/girder/girder/blob/master/CHANGELOG.rst)

```
# Historical References and Documentation

This page exists for convenience only. It may references commits and/or unmaintained documentation.

## Deployment Alternatives

* Running on Elastic Beanstalk: Support dropped in aa6460b
[...]
```

**Comment by brianhelba** [comment]
> Two suggestions:
> 
> * document these historical  information on the Girder wiki provided by GitHub (example of text provided below)
> * and/or add entries in the [CHANGELOG](https://github.com/girder/girder/blob/master/CHANGELOG.rst?rgh-link-date=2020-07-03T20%3A54%3A55Z)

The removed information is obsolete, and I think it would be counterproductive clutter to keep it on a wiki. 

However, it'd be good to note in the `CHANGELOG` that the installation docs and supported methodologies have been improved and updated. I'll make that change.

**Comment by jcfr** [comment]
> it'd be good to note in the CHANGELOG that the installation docs and supported methodologies have been improved and updated. I'll make that change.

:+1: 

Thanks @brianhelba

**Pull request merged**
