### PR TITLE
Make job status values extensible

### PR DESCRIPTION
**Pull request by zachmullen**
We add a simple event hook for allowing job status values
beyond the ones built into the jobs plugin.

We will need this for https://github.com/Kitware/romanesco/pull/200

### CODE REVIEW

**Comment by cpatrick** [comment]
LGTM. I'd like some more docs, but this *is* a simple feature.

**Comment by zachmullen** [comment]
@cpatrick good thought, I added more docs.

**Comment by zachmullen** [comment]
@cpatrick PTAL I've also made new changes to the web client code related to job statuses.

**Comment by cpatrick** [comment]
I like the docs and changes. I'm slightly bothered by the duplication between JS and Python, but I'm not sure the best way around that. All things considered, LGTM.

**Pull request merged**
