### PR TITLE
Move to an official release of cmake.

### PR DESCRIPTION
**Pull request by manthey**
We were on a release candidate.  This is the first official release that supports everything we want.  The only relatively new feature we need from cmake is the ability to report our coverage files to cdash.

### CODE REVIEW

**Comment by zachmullen** [comment]
LGTM

**Comment by aashish24** [comment]
CMake 3.2.1 is out. Why use a older version?

**Comment by manthey** [comment]
As per a conversation on girder-developers, we should should use the oldest official version that supports what we need, so as to illustrate the minimum dependencies.  We should occasionally test separately with the latest cmake (and with release candidates).

**Comment by aashish24** [comment]
Sure but this is just for travis right? But please do what we all agree.

**Comment by manthey** [comment]
Yes, just for Travis.  The nightly builds can use a different cmake version.

**Comment by aashish24** [comment]
oops.. hit send too soon. I guess we want users to use 3.1 as well so using a older version probably make sense.

**Comment by zachmullen** [comment]
There is still the question of what to put as our `
cmake_minimum_required(VERSION`. Right now it's set to 2.8.6, since that works fine for everything except coverage reporting to CDash. I'm fine with keeping it at that since the latest version in APT is still only 2.8.12. We can rethink that value perhaps once the APT package gets updated, but I have no idea on a timeline for that.

**Comment by jbeezley** [comment]
The next release is set to get 3.0.2.

https://launchpad.net/ubuntu/vivid/amd64/cmake/3.0.2-1ubuntu2

**Pull request merged**
