### PR TITLE
Buttons that looked disabled were actually not

### LINKED ISSUE #1498: Disabled buttons are not actually disabled
We are adding the disabled class to make them look disabled, but not the disabled property to actually disable them.

### PR DESCRIPTION
**Pull request by zachmullen**
Closes #1498 

I am reopening this on behalf of @vovythevov , originally was in PR #1532

### CODE REVIEW

**Comment by zachmullen** [comment]
```
Running "webpack:dev" (webpack) task
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
 - configuration.resolve.extensions[4] should not be empty. Use --force to continue.
```

That problem wasn't happening to me locally until I blew away node_modules and re-ran `npm install`, meaning this is something that changed in an upstream npm package (presumably webpack itself). @sebastienbarre any idea? Google wasn't very helpful

**Comment by sebastienbarre** [comment]
I'll check today. This is an issue I had mentioned in the PR -- the debug
options were in flux in the 2.0 beta so I added all of them and a cleanup
might be needed.

**Comment by zachmullen** [comment]
That makes sense, thanks for looking into it.

**Comment by sebastienbarre** [comment]
Still working on this, I'm afraid the `grunt-webpack` plugin itself [is having issue passing an option not allowed by Webpack anymore](https://github.com/webpack/grunt-webpack/blob/master/tasks/webpack.js#L29), but it's unclear if sokra is still updating it ([I reported it](https://github.com/webpack/grunt-webpack/issues/65#issuecomment-248523613)). Might just execute webpack from grunt.

**Comment by zachmullen** [comment]
@sebastienbarre PTAL, I just pinned to the last known working version of the webpack 2.0 beta package for now.

**Pull request merged**
