### PR TITLE
Tweak javascript test cmake functions

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@zachmullen Custom jshint and jsrc settings for plugin are now supported.

**Comment by zachmullen** [comment]
Travis can't find nodejs executable.

**Comment by jcfr** [comment]
@zachmullen I expect commit ce02885 to address the issue previously reported by travis. Note that to keep the history cleaner, I simply rebased the topic.

**Comment by jcfr** [comment]
Only one failing test is reported: [server_access](http://my.cdash.org/testDetails.php?test=18796851&build=742238)

I double this is related to that set of changes.

**Comment by manthey** [comment]
Since one of the two builds in Travis worked, I expect this is a transient failure, and if you reran the travis build, it would probably not happen again.

**Comment by zachmullen** [comment]
This LGTM. Let's keep an eye on jscs and jshint to see if they add support for this in the future to allow us to remove this code.

**Pull request merged**
