### PR TITLE
Don't use except: without specifying the exception.

### PR DESCRIPTION
**Pull request by manthey**
By itself, `except:` will catch all exceptions, even, for instance, SIGINT (Control-C).  This isn't usually desired, and if it is, a comment should be added to explain why.  Rather, the default exception that should be used when you want to catch nearly all exceptions is `except Exception:`.  This lets `BaseException`s through (which includes SIGINT) while stopping all subclassed `Exception`.

### CODE REVIEW

**Comment by jbeezley** [comment]
:+1: blocking SIGINT is evil

**Comment by zachmullen** [comment]
This sounds like a good idea. Besides SIGINT, what else falls under `BaseException` and not `Exception`?

**Comment by manthey** [comment]
Besides SIGINT, `SystemExit` and `GeneratorExit`.

See https://docs.python.org/2/library/exceptions.html.

**Comment by zachmullen** [comment]
Ah, thanks. LGTM

**Pull request merged**
