### PR TITLE
Use npm-install-retry to help with intermittent errors

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by zachmullen** [comment]
The place I more often than not see the error is during the `packaging_install` test, where we are still running regular old `npm install`. Maybe we could augment that shell script to check for the presence of `npm-install-retry` and, if found, pass that as the `--npm` argument to `girder-install web`.

**Comment by zachmullen** [comment]
On second thought, that would still try to pass the `install` command line arg, so it may need more work than that unless `npm-install-retry install` is a valid command.

**Comment by cjh1** [comment]
Seems that ```npm-install-retry install``` is a valid command :smile:

**Comment by zachmullen** [comment]
Great! Here's the place: https://github.com/girder/girder/blob/master/tests/packaging/pip_install_girder.sh#L91

**Comment by cjh1** [comment]
Case in point!  :smile:

**Comment by cjh1** [comment]
@zachmullen Any pointers on getting the packaging_install test running locally, sees to be looking for a girder tarball in my source tree?

**Comment by zachmullen** [comment]
You can run `grunt package` to build the package, or just run all of the packaging tests since one of the prior ones builds the package.

**Comment by cjh1** [comment]
How are we expecting the process package to be installed,  referenced [here](https://github.com/girder/girder/blob/master/grunt_tasks/fontello.js#L2), I am getting process not found ...

**Comment by cjh1** [comment]
```
>> Error: Cannot find module 'process'
```

**Comment by zachmullen** [comment]
I thought that was part of the node standard library...

**Comment by cjh1** [comment]
Not with the old version I was using, upgrading to stable, resolve it, thanks.

**Comment by cjh1** [comment]
The "@zachmullen approved this change" sounds very grand :smile:

**Comment by zachmullen** [comment]
That feature apparently just got released live in the last few minutes, I like it.

**Comment by cjh1** [comment]
Yep, very nice.

**Pull request merged**
