### PR TITLE
Add 'mimeType' attribute to the 'linkUrl' file objects.

### PR DESCRIPTION
**Pull request by Xarthisius**
This PR is complementary to PR #1623.

### CODE REVIEW

**Comment by zachmullen** [comment]
So this stores the MIME type if it's passed, but it doesn't look like that value is read anywhere. Where would you expect this info to be used?

**Comment by Xarthisius** [comment]
@zachmullen I'm not sure I follow, where's `mimeType` supposed to be read?

**Comment by zachmullen** [comment]
In this changeset, you made it so we can store this value in the database, but it looks like we don't actually use it anywhere as far as controlling any sort of behavior. So I was just curious why you wanted it there. I'm guessing you have some plugin that is reading this value for some purpose?

**Comment by Xarthisius** [comment]
oh! yes, that's gonna be used not even in a plugin but in an external girder interface.

**Comment by zachmullen** [comment]
Ah OK.

**Pull request merged**
