### PR TITLE
Job timestamp recording

### PR DESCRIPTION
**Pull request by zachmullen**
This introduces a generic timeline widget. Here's a screenshot of an example of this widget on the job details page:

screen shot 2015-12-10 at 6 19 43 pm

ping @brianhelba we record all the timing information we need, this widget just happens to fulfill a need we also have for COVALIC. If we want a different visualization for the DSA stuff, we can certainly change the job timestamp vis.

### CODE REVIEW

**Comment by zachmullen** [comment]
TODO

- [ ] Add testing
- [ ] Implement the showLabels feature

**Comment by zachmullen** [comment]
Updated screenshot from the jobs widget.
screen shot 2015-12-11 at 11 31 42 am

**Comment by zachmullen** [comment]
Ready for review. CI still broken due to httpretty.

**Comment by zachmullen** [comment]
CI is fixed. @msmolens could you review this?

**Comment by msmolens** [comment]
:+1: LGTM

**Pull request merged**
