### PR TITLE
Vagrant provision improvements

### LINKED ISSUE #861: Ansible installer broken (and therefore vagrant is broken)
```
NOTIFIED: [restart mongodb] *************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE service name=mongodb pattern=/etc/init.d/mongodb state=restarted enabled=yes
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/zach/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile="/Users/zach/.vagrant.d/insecure_private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602 && echo $HOME/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602'"]
<127.0.0.1> PUT /var/folders/0s/12m4th657gd224y3ypp5vxk80000gn/T/tmpPCZOjs TO /home/vagrant/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602/service
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/zach/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile="/Users/zach/.vagrant.d/insecure_private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602/service; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602/ >/dev/null 2>&1'"]
failed: [default] => {"failed": true}
msg: stop: Rejected send message, 1 matched rules; type="method_call", sender=":1.45" (uid=1000 pid=6756 comm="stop mongodb ") interface="com.ubuntu.Upstart0_6.Job" member="Stop" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.47" (uid=1000 pid=6765 comm="start mongodb ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
```

### LINKED ISSUE #916: vagrant up fails on npm install during provisining
Hi,

I just forked and cloned the Girder repository on github. When I try to bring up the Girder vagrantbox, it fails on the NPM install:
~~~~
TASK: [run npm install] ******************************************************* 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE npm path=/vagrant
<127.0.0.1> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/brian/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/brian/Code/girder/.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1439320042.19-167413397287347 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1439320042.19-167413397287347 && echo $HOME/.ansible/tmp/ansible-tmp-1439320042.19-167413397287347'
<127.0.0.1> PUT /var/folders/bn/hc7234pd2cd0gxz98dn0zq_40000gn/T/tmpyO2q46 TO /home/vagrant/.ansible/tmp/ansible-tmp-1439320042.19-167413397287347/npm
<127.0.0.1> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/brian/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/brian/Code/girder/.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1439320042.19-167413397287347/npm; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1439320042.19-167413397287347/ >/dev/null 2>&1'
failed: [default] => {"cmd": "/usr/bin/npm install", "failed": true, "rc": 1}
stderr: 
npm ERR! girder@1.3.1 postinstall: `grunt init && grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the girder@1.3.1 postinstall script.
npm ERR! This is most likely a problem with the girder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt init && grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls girder
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-55-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0
~~~~

When I ssh into the vagrant box, I'm able to complete all the remaining steps (including the step that fails) in the playbook.yml file:

~~~~
    2  cd /vagrant/
    4  npm install
    5  grunt init
    6  grunt
    8  sudo python setup.py develop
   10  sudo rm /etc/nginx/sites-enabled/default 
   13  sudo cp devops/ansible/nginx.j2 /etc/nginx/sites-available/girder
   14  sudo ln -s /etc/nginx/sites-available/girder /etc/nginx/sites-enabled/girder
   15  cp devops/ansible/start_girder_in_screen.sh /home/vagrant/.
   16  cd 
   17  ls -ltra
   18  chmod 0744 start_girder_in_screen.sh 
   19  ./start_girder_in_screen.sh 
   23  sudo service nginx restart

~~~~
Wondering if others have seen this.

Brian

### PR DESCRIPTION
**Pull request by brianhelba**
* Improve Vagrantfile
 * Default VM will have 768MB of memory, which should fix npm's OOM failures.
 * Add future support for 'ansible_local' provisioner (once bugs are fixed in the next release), so Ansible will not be required on the host machine.
 * Add a message explaining where the new Girder web server is running
 * Make VM naming more clear and consistent
 * Mount the shared directory in a more obvious and accessible location.
* Update documentation with additional prerequisites
 * Pillow 3+ requires libjpeg and zlib.
 * Also note that npm 4.x should be installed on RHEL.
* Refactor Ansible playbook for Vagrant
 * Fix system dependencies.
 * Use Node 4.x.
 * Use MongoDB 3.2.

Fixes #861.
Fixes #916.

### CODE REVIEW

**Comment by brianhelba** [comment]
I've just tested this locally, and it works fine.

It purposely does not install the developer toolchain or test environment, to keep it nice and lean. If we want to add additional configurable support for other features, I'd suggest doing so as part of a more sustainable solution that uses roles (whether it's something in [ansible-role-girder](https://github.com/girder/ansible-role-girder), [GoBig](https://github.com/kitware/gobig) , or whatever we decide).

**Comment by brianhelba** [comment]
@girder/developers PTAL.

**Comment by zachmullen** [comment]
I just did a clean `vagrant up` on the head of this branch and it's getting a bunch of 404s during `TASK [System | Install dependencies]`. Is this just a temporary network problem, are you seeing this also?

**Comment by brianhelba** [comment]
Make sure your Vagrant box image is up to date. It's likely that old box images no longer have a valid Apt cache. I will work around this by forcing Ansible to do an `apt-get update`.

**Comment by brianhelba** [comment]
@zachmullen I just pushed what will hopefully fix your issue. Can you test with a fresh Vagrant box (i.e. run `vagrant destroy -f && vagrant up`)?

**Comment by zachmullen** [comment]
The provisioning now works, but when I go to localhost:9080 I see nothing.

**Comment by brianhelba** [comment]
It worked for me previously. I'll check it again in a bit.

**Comment by zachmullen** [comment]
@brianhelba I ssh'd in and it seems the problem is that mongod is not running

**Comment by brianhelba** [comment]
@zachmullen Your last commit should not be necessary. When the DEB packaged version of MongoDB finishes installing, it starts the `mongod` service automatically (a fact that has always annoyed me). Indeed, I just re-provisioned a totally fresh box without your final commit, and it works fine.

Was it a completely fresh Vagrant box, with an uninterrupted run of Ansible that generated the VM where `mongod` wasn't running? If so, I worry that `mongod` actually crashed for some reason.

**Comment by zachmullen** [comment]
It was completely fresh, I will back out my commit and try again.

**Comment by kotfic** [comment]
I can confirm that a fresh ```vagrant up``` works for me locally both with, and without zach's last commit

**Comment by zachmullen** [comment]
It worked for me this time, not sure what happened last time. LGTM.

**Comment by brianhelba** [comment]
@zachmullen Well, I think MongoDB may have crashed, which is worrying, but I'm willing to just write it off as a fluke for now.

**Pull request merged**
