### PR TITLE
OAuth improvements

### PR DESCRIPTION
**Pull request by brianhelba**
* Refactor OAuth plugin testing
 * This will make additional OAuth providers much easier to test.
* Fix a small security issue in OAuth
 * This prevents possibly private information from leaking in an error message.
* Fix an unhandled potential error in GitHub login
* Require verified email addresses from GitHub
* Update GitHub icon and colors to be more correct
* Fix Jade syntax on OAuth config page
 * Commas delimiting attributes are technically required.

### CODE REVIEW

**Comment by brianhelba** [comment]
FYI, I have a LinkedIn provider that's about 90% finished. I also have plans to implement Facebook and StackExchange soon.

**Comment by brianhelba** [comment]
Actually, there's no reason to wait on additional commits, this is strictly an improvement as-is.

@girder/developers PTAL.

**Comment by zachmullen** [comment]
Needs a merge of latest master.

**Comment by brianhelba** [comment]
Rebased on master.

**Comment by zachmullen** [comment]
LGTMITIH

**Pull request merged**
