### PR TITLE
Fixes #1284. Fix sphinx build errors

### LINKED ISSUE #1284: Add automated test for documentation generation
As of 72ff31244bf9b34d376aa662e1cea2e742338fe4, running `grunt docs` shows the following error:

    /path/to/girder/docs/developer-cookbook.rst:408: ERROR: Unknown target name: "https://midas3.kitware.com".

as well as a few warnings.

Add an automated test to detect at least the errors.

From https://github.com/girder/girder/pull/1281#discussion_r57926113

### PR DESCRIPTION
**Pull request by zachmullen**
I'm hoping this was the cause of the recent timeouts of our RTD builds, we'll see...

### CODE REVIEW

**Comment by zachmullen** [comment]
That second commit should actually fix the RTD build.

**Comment by zachmullen** [comment]
@girder/developers could someone please give this a quick QA ?

**Comment by msmolens** [comment]
I assume the `_tokenModel = ModelImporter.model('token')` line wasn't added for any side effects. If so, LGTM, except that #1284 is about adding a test, so that shouldn't be closed.

**Comment by zachmullen** [comment]
Thanks, I'll keep #1284 open

**Pull request merged**
