### PR TITLE
S3 import

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
@aashish24 the S3 import functionality now works on this topic branch. Anybody available for a QA on this?

**Comment by aashish24** [comment]
Cool! I can test it out today using an existing bucket. I will report back.

**Comment by aashish24** [comment]
Sorry for the delay. I am back to testing this branch now.

**Comment by aashish24** [comment]
As I mentioned to @zachmullen, currently we assume that we have write access to s3 bucket which in my use-case I don't. Having a option would be nice so that Girder won't test the write access and fail.

**Comment by zachmullen** [comment]
@aashish24 I just made it so you can set a read-only property on S3 assetstores. You will still need to supply credentials (simply due to a limitation of boto), but those credentials do not need to have write access to the bucket.

**Comment by aashish24** [comment]
Got further along but when importing got this error: 

500 Internal Server Error {"message": "AttributeError: AttributeError(\"'NoneType' object has no attribute 'list'\",)", "trace": [["girder/api/rest.py", 279, "endpointDecorator", "val = fun(self, args, kwargs)"], ["girder/api/rest.py", 773, "POST", "return self.handleRoute(method, path, params)"], ["girder/api/rest.py", 561, "handleRoute", "val = handler(**kwargs)"], ["girder/api/access.py", 34, "accessDecorator", "return fun(*args, **kwargs)"], ["girder/api/rest.py", 227, "wrapped", "return fun(*args, **kwargs)"], ["girder/api/v1/assetstore.py", 155, "importData", "progress=ctx, user=user)"], ["girder/models/assetstore.py", 177, "importData", "progress=progress, user=user)"], ["girder/utility/s3_assetstore_adapter.py", 339, "importData", "for obj in bucket.list(importPath, '/'):"]], "type": "internal"}

**Comment by aashish24** [comment]
This happened when I actually hit import, looks like authentication and everything else before that was good.

**Comment by zachmullen** [comment]
Interesting, I will take a look, thanks.

**Comment by zachmullen** [comment]
@aashish24 You uncovered a bug -- our validation for read only S3 assetstores was in fact not doing the verification that it could connect to the bucket. The latest commit fixes that. It seems with your credentials that you do not have read access to the bucket in question.

**Comment by zachmullen** [comment]
@aashish24 That last commit now allows anonymous S3 access. When creating/editing the assetstore, simply leave the access key and secret key fields empty, and check the read-only box, and it should work. I was able to import data from the nasanex bucket this way.

**Comment by aashish24** [comment]
awesome@ .. I will try again..

**Comment by aashish24** [comment]
Latest changes worked for me!! 

LGTM :+1:

**Pull request merged**
