### PR TITLE
Newly created jobs show on the jobs page immediately

### LINKED ISSUE #1833: Jobs page should automatically show new jobs
The eventstream is used for progress bars of new jobs, but the actual new job doesn't display on the jobs page until it's manually refreshed.

### PR DESCRIPTION
**Pull request by danlamanna**
Fixes #1833

### CODE REVIEW

**Comment by danlamanna** [comment]
Whoever has some time feel free to review. I ran into a weird issue where I discovered the JS tests already existed to test the feature this PR adds... and they've always passed (I have no idea how this is the case).

**Comment by zachmullen** [comment]
Could you link to the web client tests you mentioned?

**Comment by danlamanna** [comment]
@zachmullen https://github.com/girder/girder/blob/a801587ee2fa225d48f74966add9350186081d01/plugins/jobs/plugin_tests/jobsSpec.js#L138-L146

The issue I was encountering on this branch that I fixed, is that `collection.add` doesn't trigger a render on the widget, so I have no clue how this test is triggering render.

**Comment by zachmullen** [comment]
https://github.com/girder/girder/blob/master/plugins/jobs/web_client/views/JobListWidget.js#L43-L45

Doesn't that explain it...?

**Comment by zachmullen** [comment]
Or not, I guess `add()` doesn't trigger `g:changed`... We may want to add some screenshots before and after that to make sure the test isn't doing something unexpected.

**Comment by danlamanna** [comment]
It definitely **is** doing something wrong, I just couldn't figure out how to really debug in the environment aside from console.log calls. The `console.log` calls show it doing what it asserts, but that doesn't happen in my browser.

**Comment by matthewma7** [comment]
@danlamanna, I think I noticed the weirdness you are talking about, and @manthey help me figured it out. 
https://github.com/girder/girder/blob/a801587ee2fa225d48f74966add9350186081d01/plugins/jobs/plugin_tests/jobsSpec.js#L136-L136, the render() at the end is triggering the render()

I changed it to this in my jobs graph branch, which I think making more sense to me, meaning, ignore the first render() and explicitly trigger one with `widget.collection.trigger('g:changed');`
https://github.com/girder/girder/blob/jobs_graph/plugins/jobs/plugin_tests/jobsSpec.js#L121-L151

Now I am looking at it, I think the test is not meant for this feature specifically. The code snippet has been used a few times in the jobspec.js

**Comment by zachmullen** [comment]
As a sanity check, I did verify that the jobs appeared in the list in the jobsSpec test. This is on latest master branch. Before the call to collection.add:



And then immediately after the `waitsFor`:

**Comment by danlamanna** [comment]
@matthewma7 Not really sure how your code block works, but it did fix the issue (meaning master is broken and my branch fixes it).

**Comment by danlamanna** [comment]
@matthewma7 I switched the job list widget in this PR to listen to the `add` event, so you should be able to remove the `g:changed` trigger in your test when you rebase your branch.

This is ready for review.

**Pull request merged**
