### PR TITLE
Enforce max buffer length in SFTP download

### PR DESCRIPTION
**Pull request by zachmullen**
@cjh1 I just realized I forgot to add this change you requested yesterday. PTAL.

### CODE REVIEW

**Comment by zachmullen** [comment]
In my testing, both the CLI sftp client that comes with OSX and Filezilla use a chunk size of 32768, so 10MB seemed like a reasonable threshold.

**Comment by mgrauer** [comment]
Can you add a test for this case?

**Comment by mgrauer** [comment]
Will this message be sent out to an SFTP client?  

    'Requested chunk length (%d) is larger than the maximum allowed.' % length)

If so, maybe it would be useful to also include our max value in the message so they can change their client setting (is that something you can even change on a client?).

**Comment by zachmullen** [comment]
Sadly no. Paramiko converts all exceptions to SFTP standard status codes and messages, so clients never get to see these custom ones.

**Comment by zachmullen** [comment]
@cjh1 I'm not able to reproduce that error

**Comment by cjh1** [comment]
ok, got to the bottom of that error, not related to this change ( environmental, its a long story )

**Comment by zachmullen** [comment]
Thanks!

**Pull request merged**
