### PR TITLE
Upgrade docker-compose.yml to version 2

### PR DESCRIPTION
**Pull request by ariarijp**

### CODE REVIEW

**Comment by zachmullen** [comment]
If we are updating this version, shouldn't we upgrade to v3, which is the latest and recommended version?

**Comment by ariarijp** [comment]
Version 3 is latest and I recommend it, but version 2 is still popular.

I think we can skip version 2 for now.

**Comment by zachmullen** [comment]
What's the motivation for the change?

**Comment by ariarijp** [comment]
Hi @zachmullen ,

I prefer to use `depends_on` instead of version 1 style `link` and `ports`.

Version 2 and 3 style is easy to understand dependencies of services.

Thank you,

**Pull request closed without merging**
