### PR TITLE
Single POST uploads from the python client.

### PR DESCRIPTION
**Pull request by manthey**
Change the girder python client to use a single POST for uploads when possible.  This only applies to small files being sent to a sufficient Girder version.

This takes advantage of the change in PR #2111.  Our tests go through both the old and new code paths.

### CODE REVIEW

**Comment by zachmullen** [comment]
Has this been tested with the S3 assetstore?

**Comment by manthey** [comment]
I haven't done so.  It looks like our py_client/cli_test only tests with the default test assetstore (which is a filesystem assetstore).  A test of S3 should be added to the server_upload test for the one-post method added in PR #2111, since that would exercise the upload method in a more general way.

**Comment by manthey** [comment]
Test added.

**Comment by zachmullen** [comment]
Do we cover both branches of your new block?

**Comment by manthey** [comment]
Yes.

**Pull request merged**
