### PR TITLE
pydicom has renamed the importable library to "pydicom", from "dicom"

### PR DESCRIPTION
**Pull request by brianhelba**
See: http://pydicom.github.io/pydicom/stable/transition_to_pydicom1.html

### CODE REVIEW

**Comment by brianhelba** [comment]
@girder/developers PTAL ASAP. Until this goes in, Girder is currently broken on master. The tests are only currently passing due to a stale cache of Python dependencies.

**Comment by zachmullen** [comment]
This touches a reasonable amount of code in two different plugins; if we want a quick fix to get in ASAP, my vote would be to instead open a PR that pins us to the *old* version of pydicom (which should just be a 2 line change) and then we can review this PR less hastily.

**Comment by brianhelba** [comment]
@zachmullen That's a fair point: https://github.com/girder/girder/pull/2619

**Comment by brianhelba** [comment]
Note, I also manually tested the `dicom_viewer` and `thumbnails` plugins. Both still decode DICOM images.

**Pull request merged**
