### PR TITLE
Python client outstandingissues and inheritaccess

### LINKED ISSUE #598: Outstanding GirderClient capabilities
From #582 

- [x] add callbacks for folder/item creation
- [x] implement upload folder as item
- [x] update docstrings on functions
- [x] Make sure we can upload into top level (collection or user)

### LINKED ISSUE #651: Add ability to recursively set access control via python CLI
I imagine passing in a folder ID and having its current access control settings be pushed down through all descendents.

### PR DESCRIPTION
**Pull request by mgrauer**
Includes commits from closed PRs #613 and #653 .

Fixes #651 .  Fixes #598 .

### CODE REVIEW

**Comment by zachmullen** [comment]
```
47: ======================================================================
47: ERROR: testClientMetadataExtractor (plugin_tests.client_metadata_extractor_test.ClientMetadataExtractorTestCase)
47: ----------------------------------------------------------------------
47: Traceback (most recent call last):
47:   File "/home/travis/build/girder/girder/plugins/metadata_extractor/plugin_tests/client_metadata_extractor_test.py", line 51, in testClientMetadataExtractor
47:     client = GirderClient('localhost', int(os.environ['GIRDER_PORT']))
47:   File "/home/travis/build/girder/girder/clients/python/girder_client.py", line 108, in __init__
47:     + apiRoot
47: TypeError: cannot concatenate 'str' and 'int' objects
47:

**Comment by zachmullen** [comment]
I think we've reached a critical mass with the python client where we should go ahead and add some automated tests.

**Comment by cpatrick** [comment]
+1 on automated tests.

**Comment by zachmullen** [comment]
Closing this, it's now become a child of #685

**Pull request closed without merging**
