### PR TITLE
Fixes #1133. Allow raw responses to be specified for REST routes

### LINKED ISSUE #1133: Allow raw response to be sent without requiring generator
Right now a raw response can only be sent by returning a generator function that yields the output as a stream. In fact, "streaming" and "raw" can be orthogonal, so we should expose a simple function like `girder.api.rest.Resource.setRawResponse(self, val=True)` that a route handler could call to specify that its response should not be transformed.

ping @mgrauer this would solve the problem you described in your email just now, and would be simple to implement.

### PR DESCRIPTION
**Pull request by zachmullen**
@mgrauer @jcfr PTAL

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks. 

Beside of few nitpicks. LGTM

**Comment by zachmullen** [comment]
> getattr(cherrypy.request, 'girderRawResponse') is True:

> girderRawResponse is expected to exist.

Not sure what you mean by this... that attribute only gets set if `setRawResponse` is called, so we have to provide a default value.

**Comment by jcfr** [comment]
> Not sure what you mean by this... that attribute only gets set if setRawResponse is called

Nevermind then.

**Comment by jcfr** [comment]
LGTM :+1:

**Pull request merged**
