### PR TITLE
Add a basic, flexible job list widget

### PR DESCRIPTION
**Pull request by zachmullen**
And add an instance of it to show reverse-chronological jobs for
the currently-logged-in user in the user dropdown menu.

### CODE REVIEW

**Comment by mgrauer** [comment]
@zachmullen I've started using this in [Minerva](https://github.com/OpenGeoscience/minerva/commit/22e739e123a321ae50ef1d9bc538d2cc5828aae1).

Thanks for such a quick creation!

A few questions/requests:

  * can you make the pagination widget optional?
  * setting the desired columns from outside the widget is awkward, is there some better way that I don't know about?
  * can you make a setting where the job detail appears in the girder modal dialog?
  * I'm getting the job update notification events, but it isn't adding anything to my jobs list for new jobs.  Is there something else I need to do to?  The `tr.length` is 0 for me in `_statusChange`.


screen shot 2015-08-12 at 7 40 33 pm

**Comment by zachmullen** [comment]
> setting the desired columns from outside the widget is awkward, is there some better way that I don't know about?

Yeah, when I was experimenting with this I just changed the context:

```
with (girder.views.jobs_JobListWidget.prototype.columnEnum) {
    var cols = COLUMN_STATUS_ICON | COLUMN_TITLE;
}

new girder.views.jobs_JobListWidget({
    columns: cols,
    ...
});
```

> I'm getting the job update notification events, but it isn't adding anything to my jobs list for new jobs. Is there something else I need to do to? The tr.length is 0 for me in _statusChange.

Currently this is expected; it's only updating jobs that were already rendered. There are two ways we could achieve what you want, the easiest of which is to simply call

    jobListWidget.collection.fetch(null, true);

as soon as you know the new job has been created on the server.

As for your other requests, yes, those can certainly be done.

**Comment by zachmullen** [comment]
@mgrauer The most recent commit will help you achieve what you want, namely, pass the following options to your widget:

    triggerJobClick: true

This will override the default behavior of navigating to the job details route, and instead just trigger a `g:jobClicked` event from the widget with the job model as the first argument. You can bind to that event and show the job details in a modal dialog.

    showPaging: false

This will cause the pagination widget at the bottom not to be displayed.

**Comment by zachmullen** [comment]
This is now officially ready for your QA @mgrauer

**Comment by mgrauer** [comment]
This works in Girder, and I can use it in Minerva.  

@kotfic noticed that on the job details page, very long longs will make that logs element huge.  Perhaps some scroll overflow there?  Although that isn't even on this PR.

LGTM.  :japanese_goblin:

**Comment by zachmullen** [comment]
> Perhaps some scroll overflow there?

Good idea, feel free to open an issue for that.

**Pull request merged**
