### PR TITLE
Prevent our textareas from overflowing their containers

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by cpatrick** [comment]
LGTM.

**Comment by manthey** [comment]
You may want to check the style of, for instance, a collection with a description which consists of a very long string of non-white space characters.  It looks bad on Chrome even with this change.  I'll post a screenshot in a moment.

**Comment by zachmullen** [comment]
I see the problem you mention, this change was merely meant to make it impossible to drag the textarea bounds beyond the modal dialog container. We should put in a separate fix for the wrapping issue.

**Comment by manthey** [comment]
Sounds good.

**Pull request merged**
