### PR TITLE
Display the login name alongside first and last names

### PR DESCRIPTION
**Pull request by ronichoudhury**
This is helpful for distinguishing multiple accounts created under a single name.

### CODE REVIEW

**Comment by fogleman** [comment]
Could also drop in a `i.icon-user` before the name and it'd look like this. Just a thought. :)

screen shot 2016-06-21 at 1 19 44 pm

**Comment by zachmullen** [comment]
If you make the screen really narrow, does overflow stuff happen? I think that's mostly why I've avoided adding more text there.

**Comment by ronichoudhury** [comment]
At some point, the name text simply disappears. I'd expect it to become one
of those ugly hamburger icons instead (to maintain the ability to open the
menu).

roni

**Comment by zachmullen** [comment]
It looks like it actually flows outside the black area and just wonkily floats underneath. I think we should figure out a way to handle that text overflow. A couple options would be:

1. Just show the user icon and login name, and put the first and last name inside the dropdown as a header
2. If gravatar plugin is enabled, hide everything but the gravatar and the little dropdown icon.

**Comment by ronichoudhury** [comment]
I see the wonky floating now.

I'm not sure (1) actually fixes the problem; at some point you will still trigger the overflow behavior.

**Comment by zachmullen** [comment]
> I'm not sure (1) actually fixes the problem; at some point you will still trigger the overflow behavior.

I left this off of my original comment, but I think we need to add text-overflow styling such as ellipsis in the case of (1).

**Comment by ronichoudhury** [comment]
That being said, I can certainly implement (1) now and we can work on a more thorough solution in a separate PR. I would need some help with (2) because I've never used the gravatar stuff.

**Comment by zachmullen** [comment]
That would be great

**Comment by ronichoudhury** [comment]
Ok I'll give ellipsis-truncation a go :racehorse:

**Comment by ronichoudhury** [comment]
@zachmullen, I added a commit that implements (1) but I poked around with text-overflow and ellipsis et al. and couldn't figure out how to make it work for Girder's navbar. Could you or someone else take a look at that?

**Comment by zachmullen** [comment]
Sure, I'll give it a shot

**Comment by zachmullen** [comment]
I got the ellipsis working with some CSS3 hackage, however I removed the user fullname header from the dropdown list for now; it looks nice, but unfortunately broke assumptions for a common way that our plugins extend that menu, which is by prepending:

screen shot 2016-06-22 at 10 53 55 am

I've got a good idea for how to fix that in v2.0 to make extending the menu easier.

**Comment by fogleman** [comment]
Haven't looked at the DOM, but can the full name go outside of whatever container the plugins are prepending to?

**Comment by zachmullen** [comment]
Let's just say that's nontrivial :)

**Comment by ronichoudhury** [comment]
LGTM!

**Pull request merged**
