### PR TITLE
Remove double slash from file download URL in py client

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
I plan on cutting a girder_client release after this drops since some romanesco work I'm currently doing is using the pip installed version of girder_client.

**Comment by mgrauer** [comment]
What was this breaking?  I'm mainly interested in why our tests weren't catching this if it was an issue.

**Comment by zachmullen** [comment]
I'm using httmock to mock out girder in romanesco tests, and when comparing URLs I didn't want to have to check against "/api/v1//file/download". It doesn't really break anything that I know of, cherrypy handles it just fine.

**Comment by mgrauer** [comment]
LGTM

**Pull request merged**
