### PR TITLE
Add symlink for backwards compatible css

### PR DESCRIPTION
**Pull request by kotfic**

### CODE REVIEW

**Comment by kotfic** [comment]
@zachmullen there are some other issues with Minerva CSS,  but this resolves the bulk of the problems by ensuring bootstrap is reachable.

**Comment by brianhelba** [comment]
You can feel free to add this commit on top of my PR: https://github.com/girder/girder/pull/1161 , if you want to handle it all in once place.

**Comment by danlamanna** [comment]
LGTM (in terms of loading css)

**Comment by kotfic** [comment]
@zachmullen  @brianhelba if its ok i'd like to just get this small change in so we can address css breaks in minvera/imagespace/etc in parallel

**Comment by zachmullen** [comment]
yep, go ahead and merge

**Comment by brianhelba** [comment]
LGTM.

**Pull request merged**
