### PR TITLE
Write concern support for mongo client

### PR DESCRIPTION
**Pull request by zachmullen**
@Xarthisius here is a proposed fix for #2378 , could you test this and see if it works for you?

### CODE REVIEW

**Comment by zachmullen** [comment]
Note that this also sets read preference as a config file option -- prior to this change, we were not setting the correct option for read preference.

**Comment by danlamanna** [comment]
> Note that this also sets read preference as a config file option -- prior to this change, we were not setting the correct option for read preference.

I think maintaining a mapping between our own version of the mongo option name and the actual option name is prone to errors like these, perhaps we should just let configurations be a direct pass through to `pymongo.MongoClient` (with the exception of replica_set since it's already being supported). This would also allow support for all of the other Mongo options with no additional work (like the write concern timeout), though it looks like this may be supported via the URI already.

**Comment by manthey** [comment]
All of the Mongo options CAN be encoded in the URI.  I think the main reason for exposing them in our settings is to make it obvious that it is something that should be considered (or, perhaps, we just need more documentation).

**Comment by zachmullen** [comment]
> All of the Mongo options CAN be encoded in the URI.

This is true, but part of this is about setting sensible default values.

**Comment by danlamanna** [comment]
> I think the main reason for exposing them in our settings is to make it obvious that it is something that should be considered (or, perhaps, we just need more documentation).

I think this is still accomplishable without changing the names of the options.

> This is true, but part of this is about setting sensible default values.

Maybe this can be solved without extensive documentation by putting them in `girder.dist.cfg` to begin with, in convention with the rest of Girder's default configuration values.

**Comment by zachmullen** [comment]
@danlamanna had to resolve conflicts, could you approve again?

**Pull request merged**
