### PR TITLE
Add system consistency check for item "baseParentType" and "baseParentId"

### PR DESCRIPTION
**Pull request by brianhelba**
Also add a TODO to also check these fields for folders.

### CODE REVIEW

**Comment by brianhelba** [comment]
@manthey The plugin that I'm working on had some code which was moving items without updating folder sizes or the baseParent (forgivably, it was written before Girder even had a "move" function for items). This system consistency check will be very helpful in cleaning up our existing database. +1 for more checks to be added.

**Comment by manthey** [comment]
I get a cyclomatic complexity error when I run the tests on my machine in the item.py `checkConsistency` method.

**Comment by manthey** [comment]
Interestingly, Travis and my Ubuntu box give different results for the cyclomatic complexity because they are using different versions of the McCabe package (Travis pulls in mccabe==0.3, Ubunutu had mccabe==0.2.2).  I recommend we make the mccabe version explicit in the requirements-dev.txt.

**Comment by manthey** [comment]
I'll add a PR with the mccabe version change.

This LGTM.

**Comment by brianhelba** [comment]
@manthey Do you want me to rebase this on the latest master, to allow testing it with the new McCabe version, or are you confident in merging it now?

**Comment by manthey** [comment]
Merge away.

**Comment by brianhelba** [comment]
@manthey @zachmullen I'll let one of you do the merge. If you can do it by the end of today, that would be great (I need this commit for my production Girder instance).

**Pull request merged**
