### PR TITLE
Upgrade Girder, Minerva, Romanesco common dev requirements

### PR DESCRIPTION
**Pull request by brianhelba**
Celery changes at:
http://docs.celeryproject.org/en/latest/changelog.html

Coverage changes at:
https://coverage.readthedocs.org/en/coverage-4.0.3/changes.html

Flake8 changes at:
https://flake8.readthedocs.org/en/latest/changes.html

Flake8-Docstrings changes at:
https://gitlab.com/pycqa/flake8-docstrings/blob/master/HISTORY.rst

HTTMock changes at (raw form):
https://github.com/patrys/httmock/compare/1.2.2...1.2.4

McCabe changes at:
https://github.com/PyCQA/mccabe#changes

Mock changes at:
https://mock.readthedocs.org/en/latest/changelog.html

Sphinx changes at:
http://www.sphinx-doc.org/en/stable/changes.html

Sphix-RTD-Theme changes at:
https://github.com/snide/sphinx_rtd_theme/#changelog

prb and funcsigs are new dependencies of Mock.

### CODE REVIEW

**Comment by zachmullen** [comment]
That celery link doesn't work...

**Comment by brianhelba** [comment]
@zachmullen Fixed link.

**Comment by zachmullen** [comment]
Heh, this broke coverage and latest httpretty doesn't support python 3.

**Comment by brianhelba** [comment]
Yes, I expected Coverage to break, it's been a major version bump. I just wanted to see how Travis went.

This PR does not touch HTTPretty. However, the latest version is still broken on Python2, though now for a different reason; the reason you had reported to them upstream was fixed. See: https://github.com/girder/girder/commit/994d73b3c58d82c2c9f1c79cd4e3e5da7385bba2

**Comment by brianhelba** [comment]
@girder/developers PTAL.

To sync Minerva, I'm going to push the corresponding upgrades on top of https://github.com/Kitware/minerva/pull/259 , which currently is not scheduled to be merged until the next Girder release.

To sync Romanesco, should I make PRs to both https://github.com/Kitware/romanesco and https://github.com/girder/girder_worker ?

**Comment by zachmullen** [comment]
LGTM

**Comment by jbeezley** [comment]
I only see two minor issues.
```
Warning!!! Cyclic dependencies found:
- sphinx-rtd-theme => sphinx => <ReqPackage("sphinx-rtd-theme")>
- sphinx => sphinx-rtd-theme => <ReqPackage("sphinx")>
```

It looks like in the next release `sphinx-rtd-theme` will become [optional](https://github.com/sphinx-doc/sphinx/blob/e27a21859408c0843c0bc8de570327d6f4bd15c7/CHANGES#L9) though.

The other is that `snowballstemmer==1.2.1` (required by `sphinx`) is missing from the development requirements.

**Comment by brianhelba** [comment]
I'll add ``snowballstemmer`.

@jbeezley is the ``sphinx`` issue just printing warnings during ``pip install -r requirements-dev.txt`` or is it causing deeper problems for you?

**Comment by jbeezley** [comment]
It's a warning from [pipdeptree](https://github.com/naiquevin/pipdeptree).  The output of `pipdeptree --all` gives a good sanity check for a testing environment by giving a summary of the versions requested by various packages and possible incompatibilities.

 The warning is harmless though, I wouldn't worry about it.  It looks like it has been [resolved](https://github.com/snide/sphinx_rtd_theme/commit/9e2b17147dcf182622b5f3d9bf5e130dec924fe1) upstream.

**Comment by brianhelba** [comment]
I've added the additional changes:
* Reorganize transitive dependencies in requirements files
 * This also moves "mccabe" to be a transitive dependency in requirements-dev,
since it's never called directly.
* Add additional dependencies of Sphinx 

PTAL @jbeezley

**Comment by jbeezley** [comment]
LGTMWTIH

**Pull request merged**
