### PR TITLE
Use strict comparison in Javascript code

### PR DESCRIPTION
**Pull request by brianhelba**
Coercive comparison is almost always not the desired behavior, and can be a source of bugs.

Regex: 's/([^=!])==([^=])/\1===\2/g'
       's/!=([^=])/!==\1/g'

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I tend to agree with @brianhelba. Is there any style/content checking for `===`? Otherwise I can see `==` creeping back in.

**Comment by cpatrick** [comment]
I'm surprised this isn't in our javascript style checks... Oh, okay. Now that I look at it, these are jade and test specs. Can we check that?

**Comment by jbeezley** [comment]
Yeah, it's in our [jshint config](https://github.com/girder/girder/blob/master/tests/jshint.cfg#L32).  Testing the js embedded inside jade would be more difficult though.

**Comment by jeffbaumes** [comment]
Can we add a test that performs @brianhelba's regex replace on these other files and fail if it is anything other than a no-op? I don't want to try to replicate jslint but for something easy like this it seems tractable.

**Comment by danlamanna** [comment]
[jade-lint](https://github.com/benedfit/jade-lint) doesn't seem to support it yet but seems very active. Might be something to incorporate in the future? #lintAllOfTheThings

**Comment by zachmullen** [comment]
Definitely looks promising. https://github.com/benedfit/jade-lint/issues/35

**Comment by jbeezley** [comment]
Hmmm... I wonder if it would be crazy to allow passing javascript to different linter somehow.

**Comment by brianhelba** [comment]
Amended my commit with 3 extra line changes that I missed before.

If anyone wants to augment this PR with an extra commit on top of this one with a style check / linter for template / test spec files, you're certainly welcome to.

**Comment by brianhelba** [comment]
Let's followup discussion over in https://github.com/girder/girder/issues/944 .

**Pull request merged**
