### PR TITLE
Improve presentation of item_tasks task list

### PR DESCRIPTION
**Pull request by msmolens**
image

### CODE REVIEW

**Comment by jeffbaumes** [comment]
This is great, but there doesn't seem to be pagination, even if there are 4 screens of analyses (I reloaded pysciencedock into several folders). Is the pagination set to a large number per page?

**Comment by msmolens** [comment]
Indeed, the default page size for ItemCollection is 100: https://github.com/girder/girder/blob/36970b8afe3fbf0211d86347ac4c2a58400dbcf4/clients/web/src/collections/ItemCollection.js#L8.

I'll improve this behavior.

**Comment by jeffbaumes** [comment]
Looks way better, though I'd maybe increase the page size to something like 20. Seems like you should be sure to fill screens on larger monitors so there is no blank space.

**Comment by msmolens** [comment]
I increased the page size to 20. If users need more flexibility we can always expose this parameter in the UI.

**Pull request merged**
