### PR TITLE
Trigger events upon importing files and folders into filesystem assetstore

### PR DESCRIPTION
**Pull request by Xarthisius**
This PR adds few additional events that happen while files are imported

### CODE REVIEW

**Comment by zachmullen** [comment]
What's the use case here that you only want to do this in the case of a filesystem assetstore?

**Comment by Xarthisius** [comment]
I'm storing physical `importPath` in items/folder metadata. It only makes sense for import not general upload/creation

**Comment by zachmullen** [comment]
That makes sense. I think we should remove the `_` from the beginning of the event name if we plan to make it officially supported. Also, having the type in both the event name and as a field in the info is redundant, so I think we should either have a single event and pass the `type` field, or have two different events and remove the `type` field.

**Comment by zachmullen** [comment]
LGTM

**Pull request merged**
