### PR TITLE
Acl widget issues

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
Depends on #682 (only the last commit here is this topic)

**Comment by cpatrick** [comment]
Does the ACL Widget have testing coverage? This LGTM if we add an issue for that (or better yet, a test).

**Comment by zachmullen** [comment]
[It has decent coverage currently](http://my.cdash.org/viewCoverageFile.php?buildid=724278&fileid=1274687).

**Comment by cpatrick** [comment]
In that case, this LGTM--without qualification.

**Pull request merged**
