### PR TITLE
Deprecate girder-users mailing list, transition to discourse

### PR DESCRIPTION
**Pull request by zachmullen**
Mailman is dead, long live discourse

### CODE REVIEW

**Comment by zachmullen** [comment]
When this is merged, I will email the girder-users list with a note about the deprecation and a link to the discourse forum.

**Comment by danlamanna** [comment]
Does this warrant one of those fancy badge things?

https://meta.discourse.org/t/is-there-a-nice-gh-badges-ala-shields-io-images-design-to-put-in-readme-to-link-from-github-to-our-hosted-discourse/65105/5

**Comment by zachmullen** [comment]
@mgrauer is going to look at the site on Thursday afternoon. After that we can pull the trigger.

**Comment by zachmullen** [comment]
@mgrauer good to move?

**Pull request merged**
