### PR TITLE
Migration guide template

### PR DESCRIPTION
**Pull request by zachmullen**
To add stuff to this, base off of 2.0-integration and merge back into it.

### CODE REVIEW

**Comment by zachmullen** [comment]
@girder/developers any objections to this template? We'll want to start filling it in soon.

**Comment by sebastienbarre** [comment]
For later reference, also check the Migration section I wrote for the web client code (and plugins) in #1476

**Comment by manthey** [comment]
Will information on how files have been rearranged (views versus js, for instance) going to be in the most relevant subsection (web client changes in this case)?  Does there need to be a section on how to webpack-ify the plugin?

**Comment by sebastienbarre** [comment]
Feel tree to pilfer my section and rearrange it the way you want. I'm not sure I would maintain two documents about client migration for now, before we hear from "big" plugins (not in girder/girder) and their experience migrating to 2.0? Either way I'm planning on updating the PR description with their feedback.

**Comment by zachmullen** [comment]
@manthey yes, I want this file to be the authoritative guide for how to migrate plugins, use webpack, and everything else that requires downstream changes. I anticipate there will be several sub-headings underneath each of the three sections. This PR is just for the top level headings, so if we find that to be a sensible organization, we can go ahead and merge.

**Comment by manthey** [comment]
The basic format LGTM.

**Pull request merged**
