### PR TITLE
Unpin cherrypy version in setup.py

### PR DESCRIPTION
**Pull request by zachmullen**
If this fails, I'll close this.

### CODE REVIEW

**Comment by manthey** [comment]
This had repercussions on the slicer_cli_web plugin.  See https://github.com/girder/slicer_cli_web/pull/34.

**Comment by zachmullen** [comment]
thanks @manthey , I think it would be a good idea to handle the encoding of text types in Girder's handling of raw responses, can you think of any reason not to do so?

**Comment by manthey** [comment]
I think that would be good.  CherryPy < 8 was using the code:
```
if isinstance(chunk, six.text_type):
   chunk = chunk.encode('ISO-8859-1')
```

I think that if we are going to do that, it would be better to use UTF-8 than ISO-8859-1, as (to me) that would be more expected.

**Comment by zachmullen** [comment]
Yeah, UTF8 for sure since that's what we use throughout Girder.

**Pull request merged**
