### PR TITLE
Set Access-Control-Expose-Headers on cross origin requests

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
@girder/developers PTAL, we haven't had a need to set this until now since we have a non-simple header that clients will want to inspect on XHR responses. I didn't bother adding it to the web client UI, I doubt anyone will want to change the default value anytime soon, and if they do they can use the REST API.

**Comment by manthey** [comment]
Good.  I'd like to see this in the 2.x-maintenance branch as well.

**Comment by zachmullen** [comment]
@manthey is `Girder-Total-Count` on 2.x-maintenance?

**Comment by manthey** [comment]
@zachmullen Yes, it was the last PR merged before we decoupled from master.

**Comment by zachmullen** [comment]
@manthey if you mark approval, I will merge this.

**Pull request merged**
