### PR TITLE
Fixes #925. Read-only s3 assetstores shouldn't query untracked uploads

### LINKED ISSUE #925: Cannot delete NEX-DCP30 S3 assetstore
Trying to delete an asset store with the following values:
```
Type: S3
Bucket: nasanex
Path prefix: NEX-DCP30
Access key ID:
Secret access key:
Service:
```

I recieve a 403 error with the following response

```
message: "S3ResponseError: S3ResponseError: 403 Forbidden↵<?xml version="1.0" encoding="UTF-8"?>↵<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F7620A9CA788F786</RequestId><HostId>Ek3ChCUDpiF9Nyko8YVgdsmhJgpbMxJE62e914dqoauzVhqa7gtqQCT5LoluxWJo5Hd1PCLWX/4=</HostId></Error>"
trace: [["girder/api/rest.py", 295, "endpointDecorator", "val = fun(self, args, kwargs)"],…]
0: ["girder/api/rest.py", 295, "endpointDecorator", "val = fun(self, args, kwargs)"]
1: ["girder/api/rest.py", 777, "DELETE", "return self.handleRoute('DELETE', path, params)"]
2: ["girder/api/rest.py", 583, "handleRoute", "val = handler(**kwargs)"]
3: ["girder/api/access.py", 34, "accessDecorator", "return fun(*args, **kwargs)"]
4: ["girder/api/rest.py", 243, "wrapped", "return fun(*args, **kwargs)"]
5: ["girder/api/v1/assetstore.py", 244, "deleteAssetstore", "self.model('assetstore').remove(assetstore)"]
6: ["girder/models/assetstore.py", 82, "remove", "adapter.untrackedUploads([], 'delete')"]
7: ["girder/utility/s3_assetstore_adapter.py", 478, "untrackedUploads", "multipartUpload.cancel_upload()"]
8: ["/home/kotfic/.venvs/NEX/lib/python2.7/site-packages/boto/s3/multipart.py", 330, "cancel_upload",…]
9: ["/home/kotfic/.venvs/NEX/lib/python2.7/site-packages/boto/s3/bucket.py", 1820,…]
type: "internal"
```

I am logged in as the admin user. All items have been removed that refer to the asset store and the delete button is 'clickable.'

### PR DESCRIPTION
**Pull request by zachmullen**
@kotfic PTAL. I reproduced what you were seeing with the nasanex bucket in readonly mode, and with this change was able to delete it.

### CODE REVIEW

**Comment by zachmullen** [comment]
Also ping @manthey since you wrote this code originally

**Comment by manthey** [comment]
This change looks good.  Should there be a test?

**Comment by zachmullen** [comment]
@manthey ping

**Comment by kotfic** [comment]
@zachmullen @manthey This fixes the issue I was seeing in minerva,  LGTM FWIW

**Comment by manthey** [comment]
Thanks for adding the test.  LGTM, too.

**Pull request merged**
