### PR TITLE
Turn off coveralls for now

### PR DESCRIPTION
**Pull request by zachmullen**
After the nice side-by-side evaluation of codecov vs. coveralls, I think codecov wins out.

If anyone has a strong preference for coveralls, please speak up on this thread.

ping @jbeezley

### CODE REVIEW

**Comment by cjh1** [comment]
Just for future reference, what are the main features that gives codecov the edge?

**Comment by zachmullen** [comment]
Their features are remarkably similar, but the presentation of codecov is better looking and a bit easier to navigate (matter of opinion, of course). Coveralls website hurt my eyes to use.

**Comment by zachmullen** [comment]
The interactive sunburst visualization is kind of neat too. https://codecov.io/gh/girder/girder/branch/2.0-integration

**Comment by cjh1** [comment]
Yes, I like that viz too :smile:

**Pull request merged**
