### PR TITLE
Fixes #1247. Don't pass invalid enabled plugins

### LINKED ISSUE #1247: missing enabled plugins break plugin page
@cdeepakroy just ran into this. He had an external plugin that he had enabled, but then removed its directory. It then made the plugin management UI throw errors anytime a plugin was turned on.

### PR DESCRIPTION
**Pull request by zachmullen**
@girder/developers PTAL

### CODE REVIEW

**Comment by manthey** [comment]
Does this properly disable plugins that required the missing plugins?  (I haven't looked if it does or not).

**Comment by zachmullen** [comment]
Those will work as before, showing the unmet dependency error message, and can be disabled normally without error.

**Comment by zachmullen** [comment]
Does someone have time to review this today? I'd like to get this bug fixed ASAP.

**Comment by manthey** [comment]
I started girder with a missing plugin, and another plugin requiring the missing one is shown as "On", but cannot be toggled (the control is disabled).

Unrelated, since a style change some weeks ago, when plugins are turned off, the control is blank (it doesn't have the word "off" or any other indicator of its state), which seems confusing.

**Comment by zachmullen** [comment]
> I started girder with a missing plugin, and another plugin requiring the missing one is shown as "On", but cannot be toggled (the control is disabled).

Hm, I'll take a look at this.

>  the control is blank (it doesn't have the word "off" or any other indicator of its state), which seems confusing.

This was actually done because bootstrap-switch appeared to break their own styling in a recent update, which was causing the word "OFF" to break and the second F to flow onto a new line. I couldn't find an easy fix so I removed the text for now.

**Comment by danlamanna** [comment]
> I started girder with a missing plugin, and another plugin requiring the missing one is shown as "On", but cannot be toggled (the control is disabled).

This symptom (and that of #1247) are just side effects of the weird state Girder is in where a plugin is enabled that doesn't exist anymore. I wouldn't be surprised if more of these types of bugs popped up given this is a scenario that isn't immediately obvious to program for.

That being said, I think one solution (which would make this PR unnecessary) is for plugins (and their dependent plugins) to be immediately disabled when they fail to load due to not existing on disk. Definitely interested to hear what others think about that though.

**Comment by zachmullen** [comment]
@manthey I fixed the bug you discovered, PTAL.

**Comment by manthey** [comment]
LGTM.

**Pull request merged**
