### PR TITLE
Require six >= 1.9 as we need viewitems

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by jbeezley** [comment]
The change LGTM, but the error Travis threw doesn't look like one of the normal spurious errors.

```
53: ======================================================================
53: FAIL: testTemporaryPassword (tests.cases.user_test.UserTestCase)
53: ----------------------------------------------------------------------
53: Traceback (most recent call last):
53:   File "/home/travis/build/girder/girder/tests/cases/user_test.py", line 563, in testTemporaryPassword
53:     self.assertStatusOk(resp)
53:   File "/home/travis/build/girder/girder/tests/base.py", line 188, in assertStatusOk
53:     self.assertStatus(response, 200)
53:   File "/home/travis/build/girder/girder/tests/base.py", line 209, in assertStatus
53:     self.fail(msg)
53: AssertionError: Response status was b'403 Forbidden', not 200. Response body was:
53: {
53:     "message": "Old password is incorrect.",
53:     "type": "access"
53: }
53: 
53: ----------------------------------------------------------------------
53: Ran 12 tests in 14.144s
53: 
53: FAILED (failures=1)
```

**Comment by cjh1** [comment]
@jbeezley I restarted the build and it seems to have passed, looks like a new sporadic error?

**Comment by jbeezley** [comment]
Yeah, looks good.  Another race condition to look out for I guess.

**Comment by brianhelba** [comment]
@cjh1 Can you please be sure to delete your branch once it's merged?

I'll go ahead clean up this, https://github.com/girder/girder/pull/1148 , and https://github.com/girder/girder/pull/1147 now.

**Pull request merged**
