### PR TITLE
Expose reuseExisting in api for item create

### LINKED ISSUE #1512: Midas3 migration script: items are duplicated if they already exist

### PR DESCRIPTION
**Pull request by fogleman**
I was thinking this could be used to fix #1512... but now not so sure. Still might be handy though, so here you go.

### CODE REVIEW

**Comment by zachmullen** [comment]
LGTM

**Comment by zachmullen** [comment]
Let's add a test.

**Comment by fogleman** [comment]
@zachmullen done, take another look

**Comment by zachmullen** [comment]
LGTM

**Pull request merged**
