### PR TITLE
Add LinkedIn provider to OAuth plugin

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by brianhelba** [comment]
This depends on https://github.com/girder/girder/pull/1237 , for the icons to work correctly.

**Comment by brianhelba** [comment]
@girder/developers Ready for review. PTAL.

**Comment by zachmullen** [comment]
LGTM

**Comment by brianhelba** [comment]
FYI, I also plan to add StackExchange (which seems worthwhile) and Facebook (which SlideAtlas needs for historical reasons).

@zachmullen Are there any other providers you'd like to see? 

Otherwise, we can move on to worry about #1184 and LDAP, once the last additional providers are added

**Comment by zachmullen** [comment]
Google, Facebook, and Twitter seem to me to be the "big 3" right now. I'm fine with waiting on any other providers until we actually need or want them.

**Pull request merged**
