### PR TITLE
System setting to disable logging in with a password

### PR DESCRIPTION
**Pull request by zachmullen**
@manthey PTAL

### CODE REVIEW

**Comment by manthey** [comment]
If you have no oauth providers enabled and you disable password login, there are no login methods.  Should we guard against that in any way?

**Comment by jeffbaumes** [comment]
@manthey It would seem difficult to know whether another login mechanism (could be oauth or something else in the future) was enabled through a plugin, so I'd suggest leaving it to the admin to do the right thing.

**Comment by manthey** [comment]
Then, I'll assume that if an admin turns off all login methods for all admins, that someone has access to the database so they can turn them back on the hard way.

**Comment by brianhelba** [comment]
@jeffbaumes @manthey Apropos to administrators managing to lock themselves out of their own Girder instance, note that we currently have [a block of code which verifies and enables a user if they're the only user in the instance](https://github.com/girder/girder/blob/master/girder/models/user.py#L124). Since the default setting is to not require verification / enablement, this is another case of not trusting / expecting admins to "to the right thing".

I'm generally uncomfortable with putting in settings that allow admins to break their own instance. Can we add some additional guards to prevent this case, or warn users?

Also, I'd like to look further into how we're passing public settings. Please hold on merging until I have a chance to review further.

**Comment by danlamanna** [comment]
Can we add a changelog entry under added features?

**Pull request merged**
