### PR TITLE
Ansible file improvements

### PR DESCRIPTION
**Pull request by brianhelba**
See individual commit messages for details.

### CODE REVIEW

**Comment by brianhelba** [comment]
Full disclosure: I haven't had a chance to test this on a completely-fresh OS yet, but I pulled these changes from a working script on another project.

Do we have a procedure for testing this script?

**Comment by zachmullen** [comment]
@brianhelba to my knowledge we don't have any automated testing for this script. Vagrant seems like the right tool to use to get a fresh OS for testing.

**Comment by zachmullen** [comment]
@brianhelba did you have a chance to test these out yet?

**Comment by zachmullen** [comment]
@brianhelba will you be able to test this out in the next few days? If not I'll go ahead and close the PR and we can re-open it when you get a chance.

**Pull request closed without merging**
