### PR TITLE
Expose coverage config as a cmake variable

### PR DESCRIPTION
**Pull request by jbeezley**
This is needed in Minerva to configure the coverage report for submission to CDash.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
```python
int(''.join([str(pow(2,i)) for i in range(4)]))
```

**Comment by zachmullen** [comment]
> `int(''.join([str(pow(2,i)) for i in range(4)]))`

Is this the new "LGTM"?

**Comment by jbeezley** [comment]
`base64.b64decode('TEdUTQ==')`

**Comment by zachmullen** [comment]
@jbeezley your change LGTM

@jeffbaumes most modern processors have barrel shifters in their ALUs, so you could save clock cycles by writing as:

    int(''.join([str(1 << i) for i in range(4)]))

:wink:

**Comment by jeffbaumes** [comment]
> Is this the new "LGTM"?

No but good idea, I should randomly do something like @jbeezley's obfuscation sometime. Let the record show I know nothing about this branch. I just liked the issue number.

**Pull request merged**
