### PR TITLE
Factor out request error handling for reuse

### PR DESCRIPTION
**Pull request by cjh1**
This allows applications to intercept error such as 404's that may have "special" meaning within an application and then delegate the rest to the Girder client. For example if the application need to test if a resource exists then they wouldn't want he 404 to be reported to the user.

### CODE REVIEW

**Comment by cjh1** [comment]
I guess an alternative to this is just change my server code not to produce 404 for not found, thoughts?

**Comment by zachmullen** [comment]
I'm fine with refactoring this out if it is helpful, did you choose to go a different route?

**Comment by cjh1** [comment]
Yep, choose to go a different route in the end, as the browser will report 404 as an error anyway its probably not good to use it to check for the existence of a resource.

**Comment by zachmullen** [comment]
FWIW, in girder we chose not to distinguish between the 404 vs. 401/403 cases for security reasons, and instead we just return the more generic 400 and say "no such resource" so that someone can't detect the existence of something to which they do not have access.

**Pull request closed without merging**
