### PR TITLE
Fixes #801. Use correct device width when rendering styles

### LINKED ISSUE #801: Girder is not mobile-friendly
While uploading / downloading of files is less likely to occur with users on mobile devices (tablets / phones), there may be uses where mobile devices are used to browse folders / items or where plugins provide additional functionality that users on mobile devices may want to access.

Currently, Girder is failing [Google's Mobile-Friendly Test](https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fgirder-test.herokuapp.com%2F). There also may be other mobile-friendliness metrics we should test against.

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
@brianhelba As the reporter of #801 do you mind giving this a quick QA when you get a minute?

**Comment by mgrauer** [comment]
Some screenshots before the fix, taken from chrome using the mobile device simulator for everything other than Desktop.

Desktop [1154 x 566]

screen shot 2015-07-01 at 3 27 04 pm

Google Nexus 7 [960 x 600]

screen shot 2015-07-01 at 3 27 21 pm

Apple iPhone 5 (the one I have :smirk: ) [320 x 568]

screen shot 2015-07-01 at 3 27 39 pm

Samsung Galaxy S4 [360 x 640]

screen shot 2015-07-01 at 3 28 00 pm

Apple iPad [1024x768]

screen shot 2015-07-01 at 3 31 02 pm

**Comment by mgrauer** [comment]
And now with the fix

Desktop [1154 x 566]

screen shot 2015-07-01 at 3 28 42 pm

Google Nexus 7 [960 x 600]

screen shot 2015-07-01 at 3 29 08 pm
 
Apple iPhone 5 (:smirk_cat:) [320 x 568]

screen shot 2015-07-01 at 3 29 39 pm

Samsung Galaxy S4 [360 x 640]

screen shot 2015-07-01 at 3 29 58 pm

Apple iPad [1024x768]

screen shot 2015-07-01 at 3 30 30 pm

I'm also including Apple iPhone 6 [375 x 667] because the username display is messed up on iPhone 5 (who's smirking now?)

screen shot 2015-07-01 at 3 42 49 pm

**Comment by zachmullen** [comment]
I didn't even know 360 pixels was a thing... I guess we don't support that yet :)

**Comment by mgrauer** [comment]
@zachmullen LGTM for the purpose of this branch, i.e., to observe the device width when rendering.

iPhone 5 display has some problems, but I think that is outside the scope here.

**Comment by zachmullen** [comment]
Thanks for taking a look

**Pull request merged**
