### PR TITLE
Item tasks improvements

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
This is very nice. The provenance information is great and very discoverable.

I think rerunning a task could be made just a bit more discoverable. Maybe a "visit setup page for this task" text that is linked - I am not being very creative this morning, I'm sure there's a better/shorter link text.

**Comment by jeffbaumes** [comment]
Looks like input files show as their Girder IDs instead of item name when re-running. It would be nice if it showed the item name like when you originally set up a task.

**Comment by jeffbaumes** [comment]
Link to re-run looks much better. Maybe it could be "with these same parameters" instead of "from these same parameters"?

**Comment by zachmullen** [comment]
> Maybe it could be "with these same parameters" instead of "from these same parameters"?

This was actually somewhat deliberate, I was trying to convey that it isn't necessarily going to run with the exact same parameters, but that these parameters are just a starting point in the configuration. I struggled with this text for a while, can you think of something good that conveys that behavior?

**Comment by jeffbaumes** [comment]
I see your reasoning @zachmullen. Let's keep that text as-is for now. Any potential solutions for the input file display issue?

**Comment by zachmullen** [comment]
Yep, that's coming soon.

**Comment by jeffbaumes** [comment]
I can confirm the file name is being set correctly now. This is still set as WIP - is it ready for final review?

**Comment by zachmullen** [comment]
I'll add a quick test for the new route then it should be good.

**Comment by zachmullen** [comment]
Ready for review

**Pull request merged**
