### PR TITLE
Fixes #726. FileSystem assetstore: Expand tilde when setting root directory

### LINKED ISSUE #726: FileSystem Assetstore: Expand ~ when setting "Root directory" property

### PR DESCRIPTION
**Pull request by jcfr**
This commit introduces a new static function named "preprocessInfo"
in the "FilesystemAssetstoreAdapter".

### CODE REVIEW

**Comment by jcfr** [comment]
```
$ ctest -R assetstore
Test project /home/jcfr/Projects/girder-build
    Start 13: server_assetstore
1/1 Test #13: server_assetstore ................   Passed    5.75 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   5.75 sec
```

**Comment by jcfr** [comment]
Wonder why travis report this:
```
!!! ABORTING, LOW CACHE DETECTED: 8 !!!

The command "python scripts/vmtest.py" failed and exited with 1 during .
```

**Comment by jcfr** [comment]
I guess this is reported by girder because the travis vm is in a bad state. 
See https://github.com/girder/girder/blob/master/scripts/vmtest.py

**Comment by cpatrick** [comment]
@jcfr Restart the job. We check that and kill the build quickly if the VM Travis gives us is less than ideal.

**Comment by jcfr** [comment]
@cpatrick Et voila

**Comment by zachmullen** [comment]
@jcfr This change is good but in a plot twist I have actually removed the section of code that you placed this in on another topic branch (https://github.com/girder/girder/pull/718/files#diff-6dd12b43ae96b7c5c0d435065c92a7c4L54). So it would be best to put this inside the `validateInfo` directly :)

**Comment by jcfr** [comment]
```
$ ctest -R assetstore
Test project /home/jcfr/Projects/girder-build
    Start 13: server_assetstore
1/1 Test #13: server_assetstore ................   Passed    7.02 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   7.04 sec
```

**Comment by zachmullen** [comment]
LGTM once travis is happy

**Pull request merged**
