### PR TITLE
Fix default parameter value for json

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@zachmullen Just noticed this!

**Comment by zachmullen** [comment]
Oops, wonder how that didn't break our tests?

**Comment by cjh1** [comment]
The test uses PUT but not PATCH, I can add a test?

**Comment by zachmullen** [comment]
Ah, I see. We never really use PATCH in girder so that makes sense. I'll cut a point release of the client once this is merged.

**Comment by cjh1** [comment]
Do you want me to add a test?

**Comment by zachmullen** [comment]
I guess if we are going to expose a `patch` method then we should test it in some way or another.

**Comment by cjh1** [comment]
I will take a look, can probably use httpmock

**Comment by cjh1** [comment]
@zachmullen PTAL I added a test for PATH

**Comment by zachmullen** [comment]
LGTMITIH

**Pull request merged**
