### PR TITLE
Add documentation linking to our cookiecutter template

### LINKED ISSUE #2503: Add a cookiecutter template for Girder plugins
Related #2128

### PR DESCRIPTION
**Pull request by jbeezley**
Closes #2503

### CODE REVIEW

**Comment by jeffbaumes** [comment]
@girder/developers this needs review. Could one or two people vet the cookiecutter?

**Comment by dorukozturk** [comment]
@jeffbaumes I will create a plugin for our nwb effort and was planning to use this.
I can be one of the reviewers.

**Comment by dorukozturk** [comment]
Cookiecutter worked for me. I pip installed the plugin and everything was smooth.

**Comment by zachmullen** [comment]
You and everyone else :)

**Pull request merged**
