### PR TITLE
RFC: Remove git version computation

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
The Backbone client now grabs the git sha at build time anyway, so I don't even know where this is being used.

**Comment by zachmullen** [comment]
@girder/developers @girder/core this has sat here for a little while now. Does anyone object to it? If not, can we mark approval?

**Comment by danlamanna** [comment]
I was waiting for @brianhelba to chime in since he changed it last.

**Comment by jcfr** [comment]
If you plan to distribute python package, I suggest to use https://github.com/warner/python-versioneer

It also support nicely the integration of the version information in the source distribution

**Comment by jbeezley** [comment]
@jcfr Would you recommend python-versioneer over [setuptools-scm](https://github.com/pypa/setuptools_scm/)?  It looks like python-versioneer doesn't have any recent commits.  Also, setuptools-scm is hosted in pypa's github org, so it would seem to be more official.

**Comment by zachmullen** [comment]
If anyone likes this change and thinks it should be merged, go ahead and mark approval. If I don't hear any disapproval before the end of the day today, I will merge.

**Pull request merged**
