### PR TITLE
Add apiUrl, patch and apiKey support to girder ansible module

### PR DESCRIPTION
**Pull request by kotfic**

### CODE REVIEW

**Comment by zachmullen** [comment]
We may want to wait and batch in one more change on this topic, #1328 adds the API key authentication option to the client that we will definitely want to support in the ansible module.

**Comment by kotfic** [comment]
@zachmullen should be a minor change,  i'm happy to wait on this until https://github.com/girder/girder/pull/1328 is merged

**Comment by zachmullen** [comment]
The other branch is now merged, so we can add API key authentication on this topic.

**Comment by kotfic** [comment]
@zachmullen PTAL,  

Note:  the big line +/- line count is because this also removes gobig roles in favor of the girder-ansible-role for provisioning the test VM via ansible-galaxy

**Comment by zachmullen** [comment]
LGTM

**Pull request merged**
