### PR TITLE
Use bson's JSON serialization for kwargs

### PR DESCRIPTION
**Pull request by cjh1**
This resolves the issue of serializing datetime objects and others.

### CODE REVIEW

**Comment by zachmullen** [comment]
Nice change, but I think we should avoid aliasing it since that may cause confusion if someone doesn't look up at the import line.

**Comment by cjh1** [comment]
@zachmullen OK, I was in two mines, just wanted to keep change to minimum ... whats the downside if a developer mistook the import for the system one?

**Comment by zachmullen** [comment]
Probably none, I guess I just prefer not to alias module names to other module names, but maybe this is a good case for it. I leave it up to you.

**Comment by cjh1** [comment]
@zachmullen I have made the change.

**Comment by zachmullen** [comment]
Lgtm

**Pull request merged**
