### PR TITLE
Allow plugins to override JSON encoding

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by zachmullen** [comment]
Hm, I'm trying to think of some other way to resolve the import cycle that doesn't break compatibility. Any good ideas?

**Comment by zachmullen** [comment]
(One obvious solution is deferring an import into a function body somewhere, but if we could avoid doing that it would be cleaner.)

**Comment by cjh1** [comment]
Yes, I thought of that, not very nice. I guess I didn't realize that the JsonEncoder is part of the public interface?

**Comment by zachmullen** [comment]
Essentially any symbol within the girder package that isn't prefixed with an underscore is fair game for downstreams to use. 😄

**Comment by cjh1** [comment]
Well we could leave the class in utility ( deprecate it if we want ) and create a copy in the new module.

**Comment by zachmullen** [comment]
I'm fine with that solution, so long as we mark the old version as deprecated.

**Comment by cjh1** [comment]
This is another alternative. In girder/event.py instead of doing ```from girder import logger``` to just ``import girder``` and change referenced to ```logger``` to ```girder.logger```, then the move it no longer required. Thoughts?

**Comment by zachmullen** [comment]
I don't think that will work since the logger is created inside girder's `__init__.py`

**Comment by cjh1** [comment]
It seems to, its the fact the logger is referenced in the import ( before it created ) that causes the problem.

**Comment by zachmullen** [comment]
Ah, you're right. That works then, let's do it.

**Comment by zachmullen** [comment]
LGTM

**Pull request merged**
