### PR TITLE
Upgrade Girder package requirements

### PR DESCRIPTION
**Pull request by brianhelba**
Boto changes at:
http://docs.pythonboto.org/en/latest/releasenotes/v2.40.0.html

cffi changes at:
https://cffi.readthedocs.io/en/latest/whatsnew.html#v1-6

CherryPy changes at:
https://github.com/cherrypy/cherrypy/blob/master/CHANGES.txt

Mako changes at:
http://docs.makotemplates.org/en/latest/changelog.html#change-1.0.4

PyMongo changes at:
http://api.mongodb.com/python/current/changelog.html#changes-in-version-3-2-2

psutil changes at:
https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#410---2016-03-12

pytz changes not available.

Requests changes at:
http://docs.python-requests.org/en/master/community/updates/

Celery changes at:
http://docs.celeryproject.org/en/latest/changelog.html#version-3-1-23

Snakebite changes at (raw form):
https://github.com/spotify/snakebite/compare/2.7.3...2.8.2

Pillow changes at:
https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#320-2016-04-01

Flake8 changes at:
https://flake8.readthedocs.io/en/latest/changes.html

Flake8-Docstrings changes at:
https://gitlab.com/pycqa/flake8-docstrings/blob/master/HISTORY.rst

HTTMock changes at (raw form):
https://github.com/patrys/httmock/compare/1.2.4...1.2.5

Mock changes at:
https://mock.readthedocs.io/en/latest/changelog.html

Sphinx changes at:
http://www.sphinx-doc.org/en/stable/changes.html

virtualenv changes at:
https://virtualenv.pypa.io/en/latest/changes.html

### CODE REVIEW

**Comment by brianhelba** [comment]
One pressing reason to make this change is that `Pillow==3.1.2` is not available via Conda.

**Comment by zachmullen** [comment]
LGTM

**Comment by brianhelba** [comment]
@kotfic Can you just verify that https://github.com/girder/girder/pull/1339/commits/f61f09b58fd541ae45c56558ad1eb03ddf42dde3 is fine?

**Comment by kotfic** [comment]
@brianhelba please bump [__version__](https://github.com/girder/girder/blob/b682529f9539a19fb813a111bac24bd87bb33c05/clients/ansible/girder.py#L37) to 0.2.2  otherwise LGTM.

**Comment by brianhelba** [comment]
@zachmullen PTAL @ https://github.com/girder/girder/pull/1339/commits/ae940338e6d931dc67d76e310b2f2f11f9474095 which works around https://github.com/girder/girder/issues/1362 .

Then this is ready to merge.

**Comment by zachmullen** [comment]
LGTM

**Pull request merged**
