### PR TITLE
Web client UI for uploading files into an item

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
Ready for review.

**Comment by manthey** [comment]
I was sort of expecting the interface to upload another file to be the a upload button (like in the g-hierarchy-actions-header) and located in the g-item-files-header, rather than an entry in the item Actions dialog.  All of the other upload points are independent icons.

**Comment by zachmullen** [comment]
Good point, I will move it to its own button.

**Comment by zachmullen** [comment]
ping @manthey

**Comment by manthey** [comment]
LGTM.

**Pull request merged**
