### PR TITLE
Make the audit log URL-encode all parameters before storage

### PR DESCRIPTION
**Pull request by brianhelba**
Continued from #3076

### CODE REVIEW

**Comment by zachmullen** [comment]
Did you actually encounter this in the wild?

**Comment by brianhelba** [comment]
@zachmullen https://sentry.io/share/issue/b3d5aa8d71514099840a23602339a06e/

The request had a query string of literally `?content...=` The dots caused the serialization failure to MongoDB.

**Comment by zachmullen** [comment]
Oh sorry, I was thinking about null characters, didn't realize this was about dots.

**Comment by brianhelba** [comment]
We've encountered null characters in production too.

**Pull request merged**
