### PR TITLE
Fix API breakage of the OAuth provider list endpoint

### PR DESCRIPTION
**Pull request by zachmullen**
@brianhelba PTAL

### CODE REVIEW

**Comment by brianhelba** [comment]
LGTM.

**Comment by brianhelba** [comment]
@zachmullen Note, we theoretically could change the plugin version back to 1.x at this point.

**Comment by zachmullen** [comment]
I thought of that, but I'm going to leave it at its current version since no harm can come of that, and since it feels a bit wrong to make a version not monotonically increase.

**Comment by brianhelba** [comment]
Fair enough; I'm not necessarily advocating the idea. We did only bump it to 2.0 an hour ago.

**Pull request merged**
