### PR TITLE
Ensure events are unbound from server fixture

### PR DESCRIPTION
**Pull request by alesgenova**

### CODE REVIEW

**Comment by cjh1** [comment]
Looks like a lot of test are failing. It looks like this approach is removing all the binding used internally as well. We may just wanted to add some cleanup code to our test case.

**Comment by cjh1** [comment]
@girder/developers Any thought on this one. Basically if you write tests for a plugin that binds to any events, each time the server fixture is used the event handler get bound again causing interesting results! It would be nice if the server fixture cleaned out its event map. Other than making a copy of the internal map ```events_mapping``` and restoring it in the fixture clean up I'm not sure how this can be achieved. Or may be we could make bind the same handler a no-op?

**Comment by danlamanna** [comment]
I talked with @cjh1 about this since it's another instance of #2530. Later this week I'll clean up/push my branch which deals with global state in Girder more generally - though that branch will likely require a good bit of discussion and review.

**Comment by jeffbaumes** [comment]
> I'll clean up/push my branch which deals with global state in Girder more generally

@danlamanna is there more code you plan on pushing here?

**Pull request closed without merging**
