### PR TITLE
Use prefix-based checking for CORS Content-Type validation

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
@jcfr I just force pushed a more robust fix.

**Comment by zachmullen** [comment]
@jcfr Thanks, that is actually what I meant to do :)

**Comment by brianhelba** [comment]
LGTM. According to RFC2046, only "text/plain" can actually have a "charset", but this is a fine way to deal with it generally.

**Comment by zachmullen** [comment]
In general, [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7) dictates that media types may contain 0 or more semicolon-delineated parameters after the type and subtype. We also see parameters in practice with the multipart/form-data declaration, which looks like:

    multipart/form-data; boundary=----WebKitFormBoundary85YOGRliKRJPFZM2

**Comment by manthey** [comment]
@zachmullen Thanks for hunting this down and fixing it.

**Pull request merged**
