### PR TITLE
Upgrade Girder, Minerva, Romanesco common requirements

### PR DESCRIPTION
**Pull request by brianhelba**
amqp changes at (not up to date):
https://github.com/celery/py-amqp/blob/master/Changelog

Celery changes at:
http://docs.celeryproject.org/en/latest/changelog.html

cffi changes at:
https://cffi.readthedocs.org/en/latest/whatsnew.html#v1-5-0

GeoJSON changes at:
https://github.com/frewsxcv/python-geojson/blob/master/CHANGELOG.rst

Kombu changes at:
http://docs.celeryproject.org/projects/kombu/en/latest/changelog.html

Pillow changes at:
https://pillow.readthedocs.org/en/3.1.x/releasenotes/3.1.0.html

PyMongo changes at:
https://api.mongodb.org/python/current/changelog.html

Requests changes at:
http://docs.python-requests.org/en/latest/community/updates/#release-and-version-history

Six changes at:
https://bitbucket.org/gutworth/six/src/1991f8b5b654f077e773f05695a08e0506b7367f/CHANGES

### CODE REVIEW

**Comment by brianhelba** [comment]
This should be merged along with: https://github.com/Kitware/minerva/pull/259 and https://github.com/Kitware/romanesco/pull/203 to bring all three projects in sync and up to date (with respect to common requirements only).

**Comment by zachmullen** [comment]
@brianhelba does this represent the full freeze? Just wanting to make sure transitive requirements haven't changed as well.

**Comment by brianhelba** [comment]
@zachmullen Yes, note that ``amqp`` and ``kombu`` are upgraded as well.

Actually, after I did ``pip install -r requirements.txt`` on a brand-new virtualenv, it appears that ``wheel`` is not a transitive requirement any more. However, that's outside the scope of this PR.

**Comment by zachmullen** [comment]
LGTM, ready whenever the others give approval.

**Comment by brianhelba** [comment]
I'll wait for them all, but do note that the requirements were already out of sync prior to this PR.

**Comment by brianhelba** [comment]
Due to the trouble mentioned in https://github.com/Kitware/minerva/pull/259 , we need to cut a new release of Girder before the Minerva PR can go in. Interestingly, there should be no downside to including this PR as part of that release though (see the Minerva PR for more info).

**Comment by brianhelba** [comment]
Actually, just to explain here, the dependencies are already out of sync between Girder and Minerva, and Girder and Romanesco. Merging this PR asynchronously with the other projects' PRs shouldn't make things worse, and is a step (necessary but not sufficient) towards making things better.

**Comment by mgrauer** [comment]
LGTM from Minerva's perspective.

**Comment by zachmullen** [comment]
Let's go ahead and merge this then.

**Pull request merged**
