### PR TITLE
WIP: Fix 404 errors caused by Swagger throbber

### PR DESCRIPTION
**Pull request by brianhelba**
This completely resolves issue #446.

### CODE REVIEW

**Comment by zachmullen** [comment]
What's the status of this PR?

**Comment by brianhelba** [comment]
This seems to operate just fine during normal use, but the test is failing due to some changes (likely bugs) with the upgraded version of Swagger. I'll give it another look, but it's not worth trying too hard over. I think we'd be best served putting efforts on this into upgrading to Swagger UI 2.1, which has substantial internal and Swagger specification changes.

**Comment by zachmullen** [comment]
Should we close this?

**Comment by brianhelba** [comment]
It works absolutely fine in operation, but the tests fail. From reading upstream bug reports, it looks like the solution is to upgrade to Swagger 2.1.

Further, while the docs claim that Swagger 2.1 is backwards comparable with the old 1.x Swagger spec (which Girder currently uses), I could not get Swagger 2.1 to work correctly with it. So, we'd also need to update the server to send down the spec in the new 2.0 format.

I give up. Let's close.

**Pull request closed without merging**
